_data/chains.json
- fixed ETI ticker
- more rpc nodes
- fixed `network_id`s
- ELLA: 1
- MIX: 1
- TSF: 1
=> more rpc nodes, fixed ETI, fixed network-ids

_data/chains.json
This change is to resolve issue #25 
I'll add correct block number when hard fork will be ready.
=> Add new chain_id for Webchain

_data/chains.json
=> Remove duplicate webchain entry

_data/chains.json
just a start - taken URLs from kethereum/networks to consolidate to this source
=> Add info_url

_data/chains.json
Hello!
I'd like to request to add High Performance Blockchain. It is a unique blockchain in the sense that all nodes are using specific hardware which speeds up the transactions times a lot, while keeping it secure through hardware encryption.
Mainnet has been live since September 2018, and it got multiple partners such as Union Pay Smart and China Electronics.
Website: https://hpb.io
Block Explorer: https://hpbscan.org
Community Web Wallet: https://hpb.blue
RPC: https://node.hpb.blue
=> Added High Performance Blockchain

_data/chains.json
Explorers: 
* https://aquachain.github.io/explorer
* https://explorer.aqua.signal2noi.se
Info: https://aquacha.in , https://aquachain.github.io
Bitcointalk ANN: https://bitcointalk.org/index.php?topic=3138231.0
Current Supply: https://aquacha.in/supply
Current Mining Algorithm: Argon2id (CPU)
=> Adds details for Aquachain (AQUA) network

_data/chains/1122334455.json
=> add ipos network

_data/chains/977.json
=> Add Nepal Blockchain Network (977)

_data/chains/162.json, _data/chains/163.json
Adding Lightstreams network blockchain as another ethereum compatible blockchain
=> Listing Lightstreams network blockchain

_data/chains/1313500.json
Name: Xerom
Ticker: XERO
Explorer: https://explorer.xerom.org
Public RPC: https://rpc.xerom.org
Website: https://xerom.org
Xerom is an Ethereum Fork with a modified Monetary policy, it also includes a new Masternode system which is run on-chain.
=> Added Xerom

_data/chains/1.json, _data/chains/100.json, _data/chains/101.json, _data/chains/11.json, _data/chains/1313114.json, _data/chains/1620.json, _data/chains/1987.json, _data/chains/2.json, _data/chains/61.json, _data/chains/61717561.json, src/main/kotlin/org/ethereum/lists/chains/ChainChecker.kt
this is work towards #75 - don't think this is a complete backfill of chains that have a slip44 id yet - but I found no way to automate this - needed to manually cross-reference ..
=> Support slip44 and initial backfill

_data/chains/6.json
https://explorer.jade.builders/?network=kotti
=> Update Kotti explorer

_data/chains/63.json
https://github.com/eth-classic/mordor
=> add mordor classic testnet

_data/chains/7.json
Thailand first  Public Blockchain.  running for 1 year 
https://exp.tch.in.th/home
=> Create 7.json for Thaichain Network

_data/chains/56.json, _data/chains/97.json
Add config for Binance Smart Chain and it's testnet. Thank you.
https://github.com/binance-chain/bsc/blob/bfb73f8068e8f6ebe94adff786d370a4b19fca1f/params/config.go#L216
=> create 56.json and 97.json

_data/chains/13.json, _data/chains/15.json
**Additions:**
- diode prenet under chain_id = 15
- diode staging under chaind_id = 13
=> Adding Diode Networks

_data/chains/420.json
Here's the submission! One question: I set `"chain": "ETH",` -- is that what you were looking for? This is a proper L2 so from a security model it is the same chain as ETH but was just curious what the field means. 
Anyway, hope this works!
=> Add Optimistic Eth

_data/chains/73799.json
https://energyweb.org
https://volta-explorer.energyweb.org/
https://coinmarketcap.com/currencies/energy-web-token/
=> add(chain-data): energy web's volta testnet (73799) added 

_data/chains/246.json
https://energyweb.org
https://explorer.energyweb.org
https://www.coingecko.com/en/coins/energy-web-token
=> add(chain-data): energy web chain (246)

_data/chains/11.json, _data/chains/200625.json, _data/chains/246529.json, _data/chains/246785.json, _data/chains/269.json, _data/chains/28945486.json, _data/chains/30.json, _data/chains/31.json, _data/chains/31102.json, _data/chains/3125659152.json, _data/chains/60.json, _data/chains/64.json, _data/chains/76.json, _data/chains/7762959.json, _data/chains/8.json, _data/chains/820.json
updating the chains repo from Trezor's Ethereum network data, so that we can switch to using your repo as a source
=> fill missing SLIP44 IDs and some misc updates

_data/chains/67.json
Hi,i want to add my chainID.
Thanks.
=> add DBChain Testnet

_data/chains/5869.json
Add Rubidium chainId/networkId
https://github.com/ethereum-lists/chains/issues/122
=> Add rubidium

_data/chains/35855456.json, _data/chains/99415706.json
Adding JOYS ( https://joys.digital/ ) and JOYS testnet (TOYS) Networks
=> Adding JOYS and JOYS testnet (TOYS) Networks

_data/chains/595.json, _data/chains/787.json
Add the chain ID file for Acala Network
SLIP PR: https://github.com/satoshilabs/slips/pull/1022
=> Add Acala Network

_data/chains/499.json
Please add Rupaya to your list on chain ids
=> Add Rupaya

_data/chains/156.json, _data/chains/50.json, _data/chains/51.json
Adding Support for XinFin
https://coinmarketcap.com/currencies/xinfin-network/markets/
=> Add Support for XinFin[XDC] Network

_data/chains/eip155-128.json, _data/chains/eip155-256.json
=> add Huobi ECO Chain info

_data/chains/eip155-218.json
SoterOne uses secure multi-party computation (MPC), differential privacy, machine learning and
blockchain technology to create a platform that integrates privacy protection,
data modeling and data sharing.
SoterOne uses the following chain ID:
- 218 (0xda) for SoterOne Mainnet
=> Add ChainID for SoterOne

_data/chains/eip155-88.json
Source: https://docs.tomochain.com/developer-guide/working-with-tomochain/tomochain-mainnet
=> Fix RPC link of TomoChain

_data/chains/eip155-17.json, _data/chains/eip155-35.json
TBWG chain is an enterprise-grade, service-centric POA blockchain platform developed by
TBWG  Based on Geth 
Thaifi  (Thaichain 2.0) is public blockchain focus on DeFi
=> add TBWG and ThaiFI  chain IDs

_data/chains/eip155-1023.json, _data/chains/eip155-1024.json
=> Add clover network ids

_data/chains/eip155-2022.json
Corresponding testnet to #179.
=> Add Beresheet testnet.

_data/chains/eip155-777.json
=> Add Ethermint Testnet

_data/chains/eip155-102.json
=> add id 102 for SGC testnet

_data/chains/eip155-1139.json, _data/chains/eip155-1140.json
update MathChain testnet rpc and infoURL
=> Update MathChain testnet rpc

_data/chains/eip155-1666600000.json, _data/chains/eip155-1666600001.json, _data/chains/eip155-1666600002.json, _data/chains/eip155-1666600003.json
https://docs.harmony.one/home/network/wallets/browser-extensions-wallets/metamask-wallet
cc @rlan35
=> Update Harmony Mainnet RPC URLs

_data/chains/eip155-1666700000.json, _data/chains/eip155-1666700001.json, _data/chains/eip155-1666700002.json, _data/chains/eip155-1666700003.json
https://docs.harmony.one/home/network/wallets/browser-extensions-wallets/metamask-wallet
=> Add Harmony testnet shards

README.md
add <https://networks.vercel.app>
=> docs: add new site

_data/chains/eip155-250.json, _data/icons/fantom.json, _data/icons/ftmscan.json
Added in explorer bit - https://ftmscan.com as well as some icons, for Fantom/FTMScan. Let me know if anything needs amending.
Thanks!
=> Update to Fantom Opera network

_data/chains/eip155-102.json
=> update project 

_data/chains/eip155-85.json, _data/chains/eip155-86.json
add the chain info of GateChain mainnet & testnet
tks
=> add GateChain mainnet&testnet

_data/chains/eip155-5197.json, _data/icons/eraswap.json
Please add EraSwap to your List of Chain ID's
=> Add EraSwap Network

README.md
=> Adds eth-chains to the usages section

_data/chains/eip155-127.json, _data/chains/eip155-721.json
Requesting to add Factory 127 Networks
=> Adding Factory 127 Network

_data/chains/eip155-137.json
https://polygonscan.com/ is a product from Etherscan team.
=> Update Matic network to include Polygonscan

_data/chains/eip155-421611.json
native currency?
source: https://twitter.com/arbitrum/status/1403102638699433984
=> Add ArbRinkeby

_data/chains/eip155-11297108109.json
Add Palm Mainnet chain definition.
=> Add Palm Mainnet 

_data/chains/eip155-124.json
add decentralized web / dWeb ethereum instance id = 124
=> add id 124

_data/chains/eip155-11297108099.json
=> Add Palm Testnet

_data/chains/eip155-85.json, _data/chains/eip155-86.json
suddenly notice the short name was used by another coin
tks
=> change the shortname and chain

_data/chains/eip155-1285.json, _data/chains/eip155-1288.json
Update Moonriver chain currency and add RPC URLs
Add occasionally used Moonshadow chain ID
=> Moonriver update, add Moonshadow

_data/chains/eip155-19.json
Please add the Songbird Network for chainId 19 - Songbird is the 'canary network' for Flare Network (chainId 14), and further details on Songbird are available at: https://flare.xyz/introducing-songbird/. Thank you!
=> Songbird Canary Network

src/main/kotlin/org/ethereum/lists/chains/Main.kt
=> Create a json file mapping shortName -> CAIP-2

_data/chains/eip155-1666600000.json, _data/chains/eip155-1666700000.json
=> Add Harmony mainnet and testnet block explorer url.

_data/chains/eip155-80001.json
* Added block explorer address 
* Changed Name & Chain to match similar changes in ``_data/chains/eip155-137.json``
=> Updated explorer address and Name to reflect similar changes to mainnet

_data/chains/eip155-59.json
Addresses:
https://bloks.eosargentina.io/address/0xf7ec51aa4ebf6dafe33652c4a4727ad48b6ca3d0
https://bloks.eosargentina.io/address/0x4884097a0d1db47bd8d10d9ac86f5d615491004a
Tokens:
https://bloks.eosargentina.io/token/0x045649470000000010420821841098db00000000
https://bloks.eosargentina.io/token/0x0349510000000000609d71495577d55600000000
=> EOS Mainnet: Change block explorer url

_data/chains/eip155-200.json
Added parent section to address [this comment](https://github.com/ethereum-lists/chains/pull/389#pullrequestreview-742601857).
=> Parent section in Arbitrum on xDai

_data/chains/eip155-57.json, _data/chains/eip155-5700.json, _data/chains/eip155-5800.json
We would like to add Syscoin and Syscoin Testnet. Please let me know if there is anything else you would like me to do.
=> Support syscoin

_data/chains/eip155-1284.json, _data/chains/eip155-1285.json, _data/chains/eip155-1286.json, _data/chains/eip155-1287.json, _data/chains/eip155-1288.json
Removing unnecessary parent relay chain name from "name".
=> Updates to Match MM

README.md
=> Add information about parent field in README

_data/chains/eip155-57.json, _data/chains/eip155-5700.json
=> Updating the rpc urls for the syscoin mainnet and testnet.

_data/chains/eip155-4002.json
- Main website: https://fantom.foundation/
- Testnet explorer: https://testnet.ftmscan.com/
=> add Fantom testnet

src/main/kotlin/org/ethereum/lists/chains/Main.kt
fixes a problem we saw in #522
=> Create .nojekyll file to make sure github picks index.html

_data/chains/eip155-998.json, _data/icons/lucky.json
=> added: lucky network mainnet

_data/chains/eip155-880.json, _data/chains/eip155-8888.json
Add Ambros Chain Mainnet and Testnet
=> Add Ambros Chain Mainnet and Testnet

_data/chains/eip155-28.json, _data/chains/eip155-288.json
Create entries for Boba Network Mainnet and Rinkeby.
=> Create Boba Network

_data/chains/eip155-201030.json, _data/chains/eip155-210309.json, _data/icons/alaya.json, _data/icons/platon.json
=> added: Alaya&PlatON testnet

_data/chains/eip155-186.json
Create eip155-186 for seele network
=> Create eip155-186 for seele network

_data/chains/eip155-25.json, _data/chains/eip155-338.json
More information can be found at https://cronos.crypto.org
=> Add Cronos mainnet beta and Update testnet

_data/chains/eip155-60000.json, _data/chains/eip155-60001.json, _data/chains/eip155-60002.json, _data/chains/eip155-60103.json, _data/chains/eip155-70000.json, _data/chains/eip155-70001.json, _data/chains/eip155-70002.json, _data/chains/eip155-70103.json
=> add Thinkium Network

_data/chains/eip155-6022140761023.json
Hi, this is my first time working with this, so let me know if I should add anything else.  Thanks for reviewing.
-Justin
=> Add Molereum network

_data/chains/eip155-26.json, _data/chains/eip155-29.json
Genesis L1 mainnet launch Nov 19, 2021
=> add Genesis L1 mainnet

_data/chains/eip155-6626.json, _data/chains/eip155-666.json
Add [Pixie Chain](https://chain.pixie.xyz) Mainnet and Testnet
=> feat: add Pixie Chain Mainnet and Testnet

.gitignore, _data/chains/eip155-192837465.json, _data/chains/eip155-356256156.json, _data/chains/eip155-486217935.json
Create entries for Gather Network (mainnet, testnet, devnet)
=> add Gather chains

_data/chains/eip155-197710212030.json, _data/chains/eip155-197710212031.json, _data/icons/ntity.json
- Create eip155-197710212030.json
- Create eip155-197710212031.json
- Create ntity.json
=> Add ntity, ntity haradev network and ntity image

_data/chains/eip155-19845.json
=> eip155-19845.json

_data/icons/btcix.json
added ipfs file for btcix network
=> btcix.json

_data/chains/eip155-57.json
Adding support for Syscoin Mainnet to the chainlist.
The mainnet is now up, so I'm adding the chain. Please review.
Thanks for your time!
=> Adding support for Syscoin Mainnet

_data/chains/eip155-1284.json, _data/chains/eip155-1285.json, _data/chains/eip155-1287.json
Updated specs for rpc and explorers and removed faucet url
=> Updates for explorers, faucet, rpc

_data/chains/eip155-7878.json
We changed forks and now needed to change the parameters.
=> Update Chain Paramaters

_data/chains/eip155-3690.json
Changed shortcode from BTTX -> BTX
=> Updated Symbol

_data/chains/eip155-1001.json, _data/chains/eip155-8217.json
Update eip155-8217.json
- remove Ozys JSON-RPC route
- add brand new Klayn Official JSON-RPC route
Update eip155-1001.json
- remove legacy Klaytn testnet JSON-RPC route
- add brand new Klayn testnet JSON-RPC route
=> changed Klaytn mainnet RPC url

eip155-9100.json
=> New chain id

_data/chains/eip155-100.json
Updated Gnosis chain, formerly xdai chain.
=> Update Gnosis chain

_data/chains/eip155-42261.json, _data/chains/eip155-42262.json, _data/icons/oasis.json
Add Emerald Paratime Mainnet and Testnet.
=> Add Emerald Paratime networks.

_data/chains/eip155-1337702.json, _data/chains/eip155-5.json, model/src/main/kotlin/org/ethereum/lists/chains/model/Chain.kt, processor/src/main/kotlin/org/ethereum/lists/chains/Env.kt, processor/src/test/resources/test_chains/invalid/eip155-1.json
Mainly to make name shorter - needs more BackFilling
=> Introduce title field

_data/chains/eip155-707.json, _data/chains/eip155-708.json
BCS Team would like to add our testnet and mainnet IDs
=> BlockChain Station

_data/chains/eip155-47805.json, _data/icons/rei.json
=> Create eip155-47805.json and rei.json

_data/chains/eip155-11297108109.json
Palm mainnet name change to just "Palm"
=> Update Palm network name

_data/chains/eip155-11111.json, _data/icons/wagmi.json
WAGMI is a high throughput testbed for EVM optimizations which is deployed on an Avalanche subnet.
=> Addition of WAGMI Chain ID

_data/chains/eip155-74.json, _data/icons/idchain.json
Nice to meet you. I would like to add IDChain to chainlist. IDChain has chainid 0x4a so I added _data/chains/eip155-74.json with a minimal config. Can you please merge it so I can do a quick test? Icons, faucets etc. to be added later. Thanks a lot.
=> Add IDChain to chainlist

_data/chains/eip155-11297108099.json, _data/chains/eip155-11297108109.json
Add RPC endpoints for the Palm network.
=> Add Palm RPC endpoints

_data/chains/eip155-87.json
Added secure RPCs and Explorer.
=> Add HTTPS RPCs and Explorer

_data/chains/eip155-108801.json
Blockchain based on ethereum clique algorithm using Proof of Authority consensus algorithm.
=> Add new blockchain BROChain

_data/chains/eip155-5869.json
=> Update explorer url

_data/chains/eip155-11155111.json
unfortunately still missing a nice infoURL, rpc(s) and a faucet
=> Add Sepolia

_data/chains/eip155-13381.json, _data/icons/phoenix.json
Added eip155-13381 and phoenix.json to complement the first file. Will the logo for the explorer be mandatory or is it optional? 
Thank you for reviewing this pull request
=> Adding Phoenix Mainnet to Chainlist

_data/chains/eip155-1197.json, _data/icons/iorachain.json
I just added the explorer link and also updated the icon for 250px with transparent png.
=> update logo and explorer added

_data/chains/eip155-8001.json, _data/icons/teleport.json
Add [Teleport](https://teleport.network/) Testnet Chain ID **8001**
Docs: https://chain-docs.teleport.network
Get Chain ID:
```bash
curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method":"net_version","params":[],"id":67}' https://evm-rpc.testnet.teleport.network | jq .result
```
=> teleport testnet

_data/chains/eip155-8000.json
Add [Teleport](https://teleport.network/) Chain ID **8000**
We will launch the teleport network in the next few weeks. 
Testnet reference #908.
=> teleport mainnet

_data/chains/eip155-43114.json
Updated Avalanche values to make it clear that the chain is the Avalanche C Chain.
=> Update Avalanche C Chain values

README.md
Just another PR adding our fork to the list.
Btw, is there any feature you'd like to see on the site? Atm thinking of adding support for more wallets
=> Add defillama's fork

README.md
Add chainlist.network
* [chainlist.network](https://chainlist.network/)
=> Add chainlist.network

README.md
Because chain list will be unavailable at 4.3
=> Replace chainlist.org with evmchainlist.org

_data/chains/eip155-258.json
```
{
"name": "Setheum",
"chain": "Setheum",
"rpc": [],
"faucets": [],
"nativeCurrency": {
"name": "Setheum",
"symbol": "SETM",
"decimals": 18
},
"infoURL": "https://setheum.xyz",
"shortName": "setm",
"chainId": 258,
"networkId": 258
}
```
=> Add Setheum - `"chainId": 258,`

_data/chains/eip155-108.json
Added scanner section to allow metamask scanner to work
=> Fix scanner for metamask

_data/chains/eip155-18.json
=> Fix Thundercore Test Net Scanner for metamask

_data/chains/eip155-234666.json
first pull request to add HAYMO testnet in chainlist
=> update haymo testnet

_data/chains/eip155-444900.json
add weelink testnet to chainlist
=> add eip155-444900.json

_data/chains/eip155-66.json
okexchain contacted us at defillama because they rebranded, submitting a pr on their behalf
=> change okexchain's name

_data/chains/eip155-335.json, _data/chains/eip155-53935.json, _data/icons/dfk.json
This PR adds the details for the DFK Chain to chainlist. DFK Chain is an evm chain launched on avalanche subnets.
=> Add DFK Chain

_data/chains/eip155-1898.json
{
"name": "BON Network",
"chain": "BON",
"network": "testnet",
"rpc": ["http://rpc.boyanet.org:8545/"],
"faucets": [],
"nativeCurrency": {
"name": "BOYACoin",
"symbol": "BOY",
"decimals": 18
},
"infoURL": "http://boyanet.org",
"shortName": "boya",
"chainId": 1898,
"networkId": 1,
"explorers": [{
"name": "explorer",
"url": "http://explorer.boyanet.org:4000",
"standard": "EIP3091"
}]
}
=> add BON Network

_data/chains/eip155-225.json, _data/chains/eip155-226.json, _data/icons/lachain.json
Github - https://github.com/LATOKEN/lachain
Web - https://lachain.io/
=> Add LACHAIN network

_data/chains/eip155-5777.json, _data/icons/swarmchain.json, _data/icons/swarmexplorer.json
This PR adds the details for the Digest Swarm Chain to chainlist. Digest Swarm Chain is an EVM chain with social trade features for society group.
=> Added Digest Swarm Chain

_data/chains/eip155-2001.json, _data/chains/eip155-200101.json, _data/icons/milkomeda.json
=> Fix wrong values in the Milkomeda network

_data/chains/eip155-168.json, _data/chains/eip155-4102.json, _data/icons/aioz.json
This PR adds the details for the AIOZ Network to chainlist. AIOZ Network is a Cosmos-based blockchain with EVM compatible.
=> Add AIOZ Network Mainnet and Testnet

_data/chains/eip155-300.json
=> Add Optimism on Gnosis Chain

_data/chains/eip155-1666600000.json, _data/chains/eip155-1666600001.json, _data/chains/eip155-1666600002.json, _data/chains/eip155-1666600003.json
This was brought up by trying to add Harmony support into sourcify through this PR: https://github.com/ethereum/sourcify/pull/648
The previously listed RPC's seem not to be official (and shard 3 endpoint was not working correctly as tested in the mentioned PR)
=> Adjust Harmony RPC's

_data/chains/eip155-2001.json
this results an error in metamask
=> shorten mADA symbol

_data/chains/eip155-79.json, _data/chains/eip155-81.json
Symbol for testnet was >6 characters and hence I was getting an error while trying to add the network. Kindly merge the fix.
=> Fix length error for symbol

_data/chains/eip155-2223.json
* add a new chain
* add rpc url
* add explorer url
=> [chain] Add new chain

_data/chains/eip155-2569.json, _data/icons/techpay.json
Added TechPay Chain Network details
=> Added TechPay Chain Network

_data/chains/eip155-880.json, _data/chains/eip155-8888.json
=> Update new ambros endpoints

_data/chains/eip155-880.json, _data/chains/eip155-8888.json
=> Update Ambros symbol

_data/chains/eip155-2612.json, _data/chains/eip155-2613.json, _data/icons/ezchain.json
Add EZChain (EZC) Chain ID: 2612 for mainet and 2613 for testnet
=> Added EZChain mainnet, testnet and icon

_data/chains/eip155-2008.json, _data/chains/eip155-2009.json, _data/icons/cloudwalk.json
both testnet and mainnet are already public and working, I will create another PR to add the RPC endpoint as soon as possible.
=> add CloudWalk networks

_data/chains/eip155-1819.json
=> add cube testnet infos

_data/chains/eip155-45000.json
See documentation https://docs.autobahn.network/
=> Update currency to TXL

_data/chains/eip155-3000.json, _data/icons/echelon.json
Add Echelon (ECH) Chain ID: 3000
=> Add Echelon (ECH)

_data/chains/eip155-4181.json, _data/icons/phi.json
=> Add PHI (PHI)

_data/chains/eip155-245022926.json, _data/chains/eip155-245022934.json, _data/chains/eip155-245022940.json, _data/icons/neon.json
Add explorer and icon for Neon networks (chainids: 245022926, 245022934, 245022940)
=> Add explorer and icon for Neon networks

_data/chains/eip155-26863.json
please help to add OasisChain mainnet, thank a lot
=> add OasisChain info

_data/chains/eip155-10946.json, _data/chains/eip155-10947.json, _data/icons/quadrans.json
Added Quadrans Blockchain (Mainnet and Testnet)
=> Add Quadrans

_data/chains/eip155-3000.json, _data/icons/echelon.json
Reverts ethereum-lists/chains#1096
=> Revert "Add Echelon (ECH)"

build.gradle, model/build.gradle.kts
replaces #1237 as ksp needs to be updated alongside
=> Update kotlin and ksp to 1.7.0

_data/chains/eip155-534.json
Updates block explorer info for Candle
=> Update eip155-534.json (Candle)

_data/chains/eip155-103090.json, _data/icons/crystal.json
Crystaleum main net is already working.
=> Add Crystaleum💎

_data/chains/eip155-10946.json, _data/chains/eip155-10947.json
Fixed third RPC server for Mainnet and RPC2 for Testnet
=> Update Quadrans RPC server list

_data/chains/eip155-7027.json, _data/icons/ella.json
Please add Ella the heart chain, thanks.
=> Add ella🎀 chain.

_data/chains/eip155-16888.json, _data/chains/eip155-88888.json, _data/icons/ivar.json
Add Ivar Chain Mainnet and Testnet.
=> Add Ivar Chain

_data/chains/eip155-3737.json, _data/icons/crossbell.json
This PR adds [Crossbell](https://crossbell.io/), a new EVM-compatible network, to the chain list.
=> Add Crossbell Network

_data/chains/eip155-2221.json, _data/chains/eip155-2222.json
Add Kava EVM Mainnet and updated Testnet EVM shortname and currency.
=> Add Kava EVM Mainnet

_data/chains/eip155-416.json, _data/chains/eip155-647.json, _data/icons/SX.json
Add SX Network Mainnet and Testnet.
=> Add SX Network Mainnet and Testnet

_data/chains/eip155-2221.json
=> Update Kava Testnet

_data/chains/eip155-107.json
=> add faucet

_data/chains/eip155-11155111.json
the rpc links from the official repo https://github.com/goerli/sepolia readme
=> add Sepolia rpc

_data/chains/eip155-100.json
Updating with the correct name/symbol for Gnosis Chain.
=> Update Gnosis Chain with correct name and symbol.

_data/chains/eip155-1297.json, _data/chains/eip155-4051.json
- Bobaopera is Boba L2 on Fantom
- Bobabase is Boba L2 on Moonbase
=> Add Bobaopera Testnet and Bobabase

_data/chains/eip155-1319.json, _data/chains/eip155-1320.json
add aitd mainnet chainid 1319, update aitd testnet chainid from 239 to 1320.
=> add aitd mainnet and update aitd testnet

_data/chains/eip155-9012.json, _data/icons/berylbit-explorer.json, _data/icons/berylbit.json
This PR introduces BerylBit into the chainlist.
=> Add BerylBit mainnet into chain list

_data/chains/eip155-3501.json, _data/icons/jfin.json
add a jfin chain mainnet
add rpc url
add explorer url
ref [PR](https://github.com/ethereum-lists/chains/pull/1101)
=> add jfin mainnet network

_data/chains/eip155-846000.json
=> Add 4GoodNetwork

_data/chains/eip155-1246.json, _data/chains/eip155-55555.json, _data/chains/eip155-64.json, processor/src/main/kotlin/org/ethereum/lists/chains/Main.kt
addresses the problem raised here: https://github.com/ethereum-lists/chains/pull/1330#issuecomment-1194176887
=> Normalize names and shortNames

_data/chains/eip155-3.json, _data/chains/eip155-4.json, _data/chains/eip155-42.json, _data/chains/eip155-421611.json, _data/chains/eip155-5.json, _data/chains/eip155-69.json
=> Update testnet native assets to canonical names

_data/chains/eip155-100.json, _data/chains/eip155-100100.json, _data/chains/eip155-300.json
=> Gnosis chains udpate

_data/chains/eip155-200202.json
https://dcspark.gitbook.io/milkomeda-getting-started/algorand/for-developers/configuring-metamask
=> Add milkomeda A1 testnet

_data/chains/eip155-144.json, _data/chains/eip155-4181.json, _data/icons/phi.json, _data/icons/phiv2.json
Updated PHI Network v1 Chain & Added PHI Network v2 Chain
=> Updated PHI Network & Added PHI V2 Smart Chain

_data/icons/phi.json, _data/icons/phiv2.json
=> Updated PHI Network Logo v1 & v2

_data/chains/eip155-1112.json
WEMIX3.0 Testnet is up now. Please add this to Ethereum-list.
=> Add WEMIX3.0 Testnet

_data/chains/eip155-2000.json, _data/chains/eip155-568.json
Add Dogechain and Dogechain Testnet
=> Add Dogechain and Dogechain Testnet

_data/chains/eip155-30.json, _data/chains/eip155-31.json
Ref:
- https://developers.rsk.co/rsk/rbtc/
=> Update RSK metadata

_data/chains/eip155-20729.json, _data/chains/eip155-820.json, _data/chains/eip155-821.json
@ligi I opened a new PR so I do not spam the branch with commits.
=> Update Callisto Network

_data/chains/eip155-10024.json, _data/icons/gonchain.json
@ligi For your review and approval, please. Thanks!
=> add gon chain

_data/chains/eip155-420666.json, _data/icons/kek.json
let's support the one [kekchain](https://t.me/kekchain)
=> add kekchain & kek logo

_data/chains/eip155-2203.json, _data/icons/ebtc.json
Added Bitcoin EVm Network Chain ID 2203
=> Add Bitcoin EVM Network

_data/chains/eip155-1294.json, _data/chains/eip155-1297.json, _data/chains/eip155-4051.json, _data/chains/eip155-4328.json, _data/chains/eip155-9728.json
- Boba BNB Testnet is Boba L2 on BNB Testnet
- Bobabeam is Boba L2 on Moonbeam
- Bobafuji is Boba L2 on Avalanche Fuji
=> Add BOBA networks

_data/chains/eip155-8080.json, tools/schema/chainSchema.json
- Removed the older Network as it is down from a long time
- Added Shardeum network which has the same chain ID
=> Update eip155-8080.json with Shardeum Network

_data/chains/eip155-11110.json, _data/chains/eip155-11115.json, _data/icons/astra.json
=> Add Astra Chain

_data/chains/eip155-1230.json, _data/chains/eip155-1231.json, _data/chains/eip155-125.json, _data/chains/eip155-126.json, _data/chains/eip155-1507.json, _data/chains/eip155-15555.json, _data/chains/eip155-20729.json, _data/chains/eip155-28.json, _data/chains/eip155-40.json, _data/chains/eip155-4051.json, _data/chains/eip155-41.json, _data/chains/eip155-4328.json, _data/chains/eip155-45000.json, _data/chains/eip155-530.json, _data/chains/eip155-5553.json, _data/chains/eip155-58.json, _data/chains/eip155-5851.json, _data/chains/eip155-59.json, _data/chains/eip155-7777.json, _data/chains/eip155-95.json, _data/chains/eip155-9728.json, tools/schema/chainSchema.json
=> Validate Shortname 

_data/chains/eip155-23118.json, _data/icons/opside.json
Add Opside Testnet, chain ID 23118
=> Add Opside Testnet

_data/chains/eip155-2077.json
Please add Quokkacoin Mainnet , and please also check the json file.
=> Add Quokkacoin Mainnet

_data/chains/eip155-3031.json, _data/icons/orl.json
=> Add Orlando Chain testnet

_data/chains/eip155-2077.json
We update the rpc  from http with a port indicated to https without a prot. Please check out if everything still work.
feel free to reply if there is anything wrong.
thank you helping.
=> Update the RPC server

_data/chains/eip155-92001.json
Replace lambda testnet rpc node
=> Replace rpc node path

.github/workflows/prettier.yml, _data/chains/eip155-92001.json
Reverts back to previous Prettier implementation using `npx prettier` directly.
=> Revert back to previous Prettier implementation

build.gradle, model/build.gradle.kts
fixes #1670 by also updating ksp
=> Use Kotlin 1.7.20

_data/chains/eip155-288.json
=> Add Bobascan explorer

_data/chains/eip155-42220.json
Add Celoscan (EIP3091) and lowercase shortName to adhere to EIP-3770
=> Add Celoscan (EIP3091) and lowercase shortName

README.md
=> Add wagmi compatible chain listings

_data/chains/eip155-8889.json
json file for Vyvo Smart Chain
=> Added Vyvo Smart Chain

_data/chains/eip155-188881.json, _data/icons/condor.json
files have been formatted with the given prettier specs.
=> please add condor network to the list

_data/chains/eip155-188881.json
=> add icon and faucet to condor network

_data/chains/eip155-248.json, _data/icons/oasys.json
*New network adding Oasys,
*http://oasys.games
=> Add new network

_data/chains/eip155-73.json
RPC : https://fncy-seed1.fncy.world
Faucet : https://faucet-testnet.fncy.world
Explorer : https://fncyscan.fncy.world
Thanks
=> add FNCY Chain

_data/chains/eip155-9528.json
=> add# QEasyWeb3 Testnet info

_data/chains/eip155-100100.json, _data/chains/eip155-10200.json
- Deprecate old Chiado chain, id 100100
- Added new Chiado chain, id 10200
=> Chiado Testnet reset

_data/chains/eip155-48.json, _data/chains/eip155-49.json, _data/icons/etmp.json
Fixed issues that the previous merge failed
=> new fork to add ETMP chains

_data/chains/eip155-1337.json
Resign back to Geth private as per EIP
=> Assign 1337 to reserved private testnet

_data/chains/eip155-1402.json
Added Polygon zkEVM Testnet (chain ID: 1402)
=> Add Polygon zkEVM Testnet (1402)

_data/chains/eip155-3306.json, _data/icons/debounce.json
=> Add Debounce Network

_data/chains/eip155-3601.json, _data/chains/eip155-3602.json
=> Addbothpando

_data/chains/eip155-800001.json, _data/icons/octaspace.json
Hello,
Please add OctaSpace network, it's one another PR, previous one was closed #1681
Thanks
=> Add OctaSpace network

_data/chains/eip155-28528.json, _data/chains/eip155-420.json, _data/chains/eip155-421613.json, _data/chains/eip155-5.json, _data/chains/eip155-534353.json
=> Remove umlaut from Goerli

_data/chains/eip155-100100.json
Avoid confusion with deprecated chain.
Related PR: https://github.com/DefiLlama/chainlist/pull/204
=> Deprecated chain name change

_data/chains/eip155-99.json
cc: @rimrakhimov I'm assuming these RPCs are not working anymore
=> Remove core.poanetwork.dev RPCs

_data/chains/eip155-6969.json
Update bridge link from beta to main:
https://lif3.com/bridge
=> Update bridge link

_data/chains/eip155-144.json, _data/chains/eip155-2203.json, processor/src/main/kotlin/org/ethereum/lists/chains/Main.kt, processor/src/main/kotlin/org/ethereum/lists/chains/model/Exceptions.kt
=> Prevent empty RPC

_data/chains/eip155-2152.json
updated RPC for chain 2152 (Findora)
=> Update RPC for Chain 2152 (Findora)

_data/chains/eip155-13000.json, _data/chains/eip155-14000.json
Please verify the request.
The SPS and SPS-Testnet is proposed and the testnet is running on.  The SPS is incubating.
Thanks a lot.
=> feat: add SPS chainId and SPSTest chianId

_data/chains/eip155-44787.json
Add blockexplorer celoscan.io operated by the Etherscan team.
=> Celo-Alfajores testnet: Update eip155-44787.json

_data/chains/eip155-956.json
Hi, I'm just wanting to register this testnet. There are not faucets at this time (though one or more will be added in the near future), and I'm not ready to expose the RPC, but I'd like to reserve the chain id because I have already put too much thought into it.
Let me know if any further work is needed on the PR
=> register μNode Testnet

_data/chains/eip155-877.json
=> eip155-877.json

_data/chains/eip155-3601.json, _data/chains/eip155-3602.json
change pando to pandoprojects as coingecko has same name as pando
=> change pando to pandoprojects

_data/chains/eip155-25888.json
Add Hammer Chain Mainnet:
chainID: 25888
networkID: 25888
Much appreciated!
=> Add Hammer Chain

httpsloader/build.gradle.kts, httpsloader/src/main/kotlin/org/ethereum/lists/chains/https/Chain.kt, settings.gradle.kts
Did this in several projects now - so moving it to a module
=> Add initial httpsloader

_data/chains/eip155-9001.json
=> Update explorer for Evmos

_data/chains/eip155-19011.json, _data/icons/home_verse.json
Create eip155-19011.json
Create home_verse.json
Thank you!
=> add home_verse

_data/chains/eip155-8272.json, _data/icons/bton.json
please add blockton blockchain to chainlist
=>  please add blockton blockchain to chainlist

_data/chains/eip155-2400.json, _data/icons/tcg_verse.json
New network adding TCG Verse,
https://tcgverse.xyz/
chain id: 2400
=> add tcg_verse

_data/chains/eip155-513100.json
Symbol ETH -> ETHF
networkId 1 => 513100
=> Fixed ethereum fair symbol and networkId

_data/chains/eip155-1337803.json
Adding public withdrawal testnet Zhejiang.
More info at: https://zhejiang.ethpandaops.io
=> add zhejiang chain

_data/chains/eip155-65010000.json
Add Autonity Bakerloo phase 0 testnet with ChainID 65010000
=> Add eip155-65010000 network

_data/chains/eip155-65100000.json
Add Autonity Piccadilly phase 0 testnet with ChainID 65100000
=> Add eip155-65100000 network

_data/icons/FastexChain, _data/icons/FastexChain.json
=> Update and rename FastexChain to FastexChain.json

_data/chains/eip155-3068.json
Adding information now that thebifrost mainnet has been released.
=> Add The Bifrost Mainnet

_data/chains/eip155-1338.json, _data/chains/eip155-1339.json
* Create eip155-1338.json for Elysium's Testnet
* Create eip155-1339.json for Elysium's Mainnet
=> add elysium chains

_data/chains/eip155-333777.json
=> Added "Oone Chain Testnet"

_data/chains/eip155-7700.json
- added 2 additional nodes to chain 7700 
- used prettier for formatting
=> Update chain 7700 (Canto) to add more RPCs

_data/chains/eip155-19.json
https://twitter.com/TowoLabs/status/1626591824008876034?s=20
=> Remove Towo Labs endpoint

_data/chains/eip155-118.json, _data/icons/acolicon.json
please add arcology network into chainlist
=> add arcology testnet

_data/chains/eip155-8453.json
Base mainnet will be launching within the next few months.
=> Add Base mainnet definition

_data/chains/eip155-67390.json
Deprecating Siriusnet old network.
=> Marking SIRIUSNET old chain deprecated

_data/chains/eip155-4061.json, _data/chains/eip155-4062.json
This PR adds entries for the Nahmii 3 Testnet and Mainnet chains.
=> Add Nahmii 3 Testnet and Mainnet

_data/chains/eip155-1339.json
Update Elysium mainnet RPC
ref: https://vulcanforgedco.medium.com/lava-on-elysium-1bd626741427#:~:text=Elysium%20Mainnet-,RPC%3A
=> Update Elysium mainnet RPC

_data/chains/eip155-418.json
Add LA Testnet chain to chainlist.
=> Add latestnet chain

_data/chains/eip155-12715.json, _data/chains/eip155-1433.json
Add rikeza Blockchain mainnet and testnet
=> Add rikeza Blockchain mainnet and testnet

maintainer_checklist.md
Updates the maintainer_checklist formatting so that the list items render properly.
=> Clean up the maintainer_checklist.md

_data/chains/eip155-8387.json, _data/icons/dracones.json
(Sorry for a dup, #2432 was closed).
I've removed all the joke mentions and any (potential?) service advertisements. Given this repo is the authoritative network source I'd love to get this merged in.
If this PR is deemed incorrect, I'd also appreciate the concrete reason as to what is deemed unfit. I followed the guidelines to the best of my knowledge: ran the gradle tests and followed the [maintainer checklist](https://github.com/ethereum-lists/chains/blob/master/maintainer_checklist.md).
=> Add eip-8387: Dracones mainnet

_data/chains/eip155-7575.json
Add ADIL Testnet chain to chainlist.
=> Add ADIL Testnet

_data/chains/eip155-195.json
Update okbchain testnet information released today!
=> Update okbhain testnet infos

_data/chains/eip155-1101.json, _data/icons/zkevm.json
Added Polygon zkEVM Mainnet (chain ID: 1101)
=> Add Polygon zkEVM Mainnet (1101)

_data/chains/eip155-910.json
=> add decentrabone testnet

_data/chains/eip155-7576.json
Add ADIL Mainnet chain to chainlist.
=> Add ADIL Mainnet

build.gradle, model/build.gradle.kts
=> Use kotlin 1.8.20

_data/chains/eip155-16688.json, _data/icons/nyancat.json
Add IRISHub testnet, also known as Nyancat.
=> Add IRISHub Testnet 

_data/chains/eip155-222000222.json
=> added kanazawa chain details

_data/chains/eip155-7576.json
- Update chain name
- Update block scan url
- Update RPC url
- https://adilchain.io/v2-opening/
=> Update ADIL Mainnet

_data/chains/eip155-2124.json, _data/icons/meu.json
I have added the MP1 Dubai-Testnet. Please check and merge it as soon as possible
=> added MP1 Dubai-Testnet

_data/chains/eip155-6502.json
Minor addition to your chain list.
=> Add Peerpay chain

_data/chains/eip155-222000222.json, _data/chains/eip155-333000333.json
we now have live explorers so have added these and updated to the production/testnet rpc urls
=> fix: update rpc and add explorers

_data/chains/eip155-534353.json
add a new explorer  for 'Scroll Alpha Testnet'
=> add a new explorer  for 'Scroll Alpha Testnet'

_data/chains/eip155-59140.json
- Update Linea URL for Infura RPC
=> Update Linea URL for Infura RPC

_data/chains/eip155-3003.json
Sorry no icon yet, will update later.
=> Add canxium mainnet

_data/chains/eip155-534353.json
update domain of one explorer for Scroll Alpha Testnet. 
https://scrollexplorer.unifra.io => https://scrollscan.co
=> Update domain of one explorer for Scroll Alpha Testnet

_data/chains/eip155-6118.json, _data/chains/eip155-6119.json, _data/icons/uptn.json
Added UPTN Mainnet Network
Added UPTN Testnet Network
Added UPTN icon
=> Add UPTN network

_data/chains/eip155-42.json
=> Update eip155-42.json: added EIP3091 to block scout

_data/chains/eip155-111000.json
=> Create Siberium Testnet eip155-111000.json

_data/chains/eip155-570.json
=> Add ANKR RPC to Rollux Mainnet

_data/chains/eip155-4001.json, _data/icons/peperium.json
I made a pin the icon at: https://peperium.infura-ipfs.io/ipfs/Qmag2hr5DQghRzKPN3oUFBkjWzqd5CndQzZeb5LfoiMCXf
Thank you!
=> Add Peperium Chain Testnet

_data/chains/eip155-570.json
This additional endpoint provided by ANKR
=> Add standalone ANKR RPC

_data/chains/eip155-6102.json, _data/icons/cascadia.json
Hello, I am creating this PR to add Cascadia Testnet Network (ID: 6102)
Local checks:
- **Check JSON Schema / validate_json (push) Successful in 8s** [Details](https://github.com/protofire/chains/actions/runs/5424340607/jobs/9863562770)
- **Run prettier / prettier (push) Successful in 27s** [Details](https://github.com/protofire/chains/actions/runs/5424340613/jobs/9863562771)
Gradle build result:
```
BUILD SUCCESSFUL in 1s
14 actionable tasks: 14 up-to-date
```
Thank you!
=> Add Cascadia testnet network data + icon

_data/chains/eip155-4759.json, _data/chains/eip155-7518.json, _data/icons/meverse.json
add meverse chain mainnet & testnet
=> add meverse chain mainnet & testnet

_data/chains/eip155-4000003.json
=> add altlayer zero gas network

_data/chains/eip155-634.json, _data/icons/avocado.json
Hey, This PR is for adding Instadapp's Avocado product on this list.
* https://avocado.instadapp.io
* https://instadapp.io
=> Added Avocado

_data/chains/eip155-7001.json
The Current RPC being used is incorrect as can be confirmed from the below ss and the discussion here https://discord.com/channels/834227967404146718/1126641259205898310
=> Update eip155-7001.json with the correct RPC

_data/chains/eip155-242.json, _data/icons/plinga.json
=> Plinga chain has been added.

_data/chains/eip155-288.json, _data/chains/eip155-2888.json, _data/chains/eip155-4328.json, _data/chains/eip155-56288.json, _data/chains/eip155-9728.json
Updating Boba network chain configs.
=> Update Boba networks

_data/chains/eip155-18686.json, _data/icons/mxczkevm.json
Hey guys we launch the first Layer3 all around the world!
=> add MXC zkEVM mainnet

_data/chains/eip155-210.json
forgot the 's' on the first commit
=> fix ssl rpc address

_data/chains/eip155-202020.json, _data/chains/eip155-75.json
=> fix RPC URL

_data/chains/eip155-7001.json
* Removed the RPC endpoint for the previous testnet.
* Updated explorer URL.
=> Zetachain Athens 3 Testnet

_data/chains/eip155-534351.json, _data/chains/eip155-534352.json, _data/chains/eip155-534353.json, _data/chains/eip155-534354.json
General update and clean up of the current statuses and URLs for Scroll chains.
=> Update Scroll Sepolia (534351) for launch & clean up other Scroll chains

_data/chains/eip155-1291.json, _data/icons/swisstronik.json
Added Swisstronik network (icons & chains folders)
Already ran `./gradlew run` and built it successfully.
=> Added Swisstronik testnet network

_data/chains/eip155-8453.json
Added developer access rpc to base mainnet
=> upgrade base rpc

_data/chains/eip155-3701.json, _data/icons/xpla.json
=> add xpla again

_data/chains/eip155-84886.json, _data/icons/aerie.json
Add AERIE MAINNET Network
Proof Of Stake
=> add aerie network

_data/chains/eip155-1.json, _data/chains/eip155-10.json, _data/chains/eip155-11155111.json, _data/chains/eip155-137.json, _data/chains/eip155-288.json, _data/chains/eip155-420.json, _data/chains/eip155-5.json, _data/chains/eip155-56288.json, _data/chains/eip155-80001.json, _data/chains/eip155-8453.json, _data/chains/eip155-84531.json, _data/chains/eip155-9728.json
Added [Tenderly Node RPCs](https://docs.tenderly.co/supported-networks-and-languages). Added HTTPS and WSS endpoints.
=> Add Tenderly Node RPCs

_data/chains/eip155-37.json, _data/chains/eip155-3701.json
=> fix xpla address, testnet deprecated

_data/chains/eip155-668.json, _data/chains/eip155-669.json
=> Create JuncaChain 668

_data/chains/eip155-61.json
This PR adds two json-rpc servers
=> Add new Ethereum Classic rpc endpoints

_data/chains/eip155-30103.json, _data/icons/canxium.json
This PR for update canxium icon and add its testnet: Cerium
=> Add Canxium icon and Testnet

_data/chains/eip155-369.json, _data/chains/eip155-942.json, _data/chains/eip155-943.json
* adds explorers
* updates status
* define slip44
=> update pulsechain networks

_data/chains/eip155-12890.json, _data/icons/qnet.json
=> Add qnet chain testnet

_data/chains/eip155-169.json, _data/chains/eip155-3441005.json
Hi @ligi and team, we have just launch manta pacific mainnet
- https://twitter.com/MantaNetwork/status/1701583217143464171
- https://pacific.manta.network/
Could you please help review this PR for adding the new network to chainlist?
Thanks a lot!
=> add manta pacific mainnet

_data/chains/eip155-44787.json
Updated the Celo Mainnet explorer link with Celo Testnet Alfajores explorer link.
=> Update explorer link for Celo Testnet Alfajores

_data/chains/eip155-38400.json
=> add ConnectorManager mainnet

_data/chains/eip155-12611.json, _data/chains/eip155-1261120.json, _data/chains/eip155-44787.json, _data/icons/astarzk.json
Both are in `incubating` state, will update when launched.
=> Add Astar zkEVM main and testnet

_data/chains/eip155-2241.json, _data/chains/eip155-9990.json, _data/icons/agung.json, _data/icons/krest.json
Changed icon files and harmonized network names
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1205538719773380
=> Update chain informations Agung & Krest

_data/chains/eip155-7700.json
=> add canto rpcs

_data/chains/eip155-59144.json
=> add l2scan in explorer

_data/chains/eip155-84532.json
We recently genesis'd the Base Sepolia testnet:
- base-org/node#115
- base-org/contract-deployments#110
- base-org/web#55
=> Add Base Sepolia testnet

_data/chains/eip155-855456.json
added [dodao.dev](https://dodao.dev)tanssi appchain
Dodao is a decentralized and permissionless task marketplace for tech talents and art creators
=> added dodao.dev tanssi appchain

_data/chains/eip155-3100.json
This PR adds an Immu3 EVM chain info
=> Add Immu3 EVM chain info

_data/chains/eip155-1.json
Flashbots Protect provides MEV protection and refunds.
=> Add Flashbots Protect RPC

_data/chains/eip155-1.json
=> Adding MEVBlocker RPC endpoints

_data/chains/eip155-68840142.json, _data/icons/frameTestnet.json
Full information can be found at frame.xyz
=> Add Frame Testnet

README.md
linking [xtools-at/smartcontract-ui](https://github.com/xtools-at/smartcontract-ui) in the readme, its an improved fork of an existing project.
it parses the chains files on build, and uses the explorer urls to show you infos on your tx as you submit them.
Demo: [Smart Contract UI](https://xtools-at.github.io/)
=> chore: added link to smartcontract-ui tool to readme

_data/chains/eip155-988207.json, _data/icons/ecrox.json
Hello ,
Please add Our Blockchain Network
=> ADD ECROX CHAIN BLOCKCHAIN

_data/chains/eip155-66988.json, _data/icons/janusnetwork.json
Hey,
Could you please add Janus Network testnet?
Thanks.
=> Janus Network Testnet added

_data/icons/frameTestnet.json
=> Update frame testnet logo

_data/chains/eip155-2241.json
One more RCP endpoint for the Krest network
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1205949228651508
=> added rpc endpoint to krest network

_data/chains/eip155-428.json
Geso Verse Production Environment Settings
=> Geso Verse add

_data/chains/eip155-2016.json
=> Adding one more RPC URL for NetZ in eip155-2016.json

_data/chains/eip155-17000.json
Add full network name in "title" similar to Sepolia, Goerli etc.
=> Add longer Holesky name

_data/chains/eip155-727.json
=> Add Blucrates Mainnet

_data/chains/eip155-653.json, _data/icons/kalichain.json
new file:   _data/chains/eip155-653.json
new file:   _data/icons/kalichain.json
=> Add kalichain 

_data/chains/eip155-11155420.json
applied minor fix to https://github.com/ethereum-lists/chains/pull/3829
"
Add OP Sepolia
See: https://docs.optimism.io/op-networks
"
=> Add OP Sepolia Testnet

_data/chains/eip155-8899.json
=> Add more RPC for JIBCHAIN L1

_data/chains/eip155-65100000.json, eip155-65100001.json
* adds new Autonity Piccadilly (Barada) Testnet
=> Update for new Autonity Piccadilly (Barada) Testnet

_data/chains/eip155-65010000.json, _data/chains/eip155-65010001.json
* Adds deprecated Autonity Bakerloo testnet (65010000)
* adds new Autonity Bakerloo testnet (65010001)
=> Autonity Bakerloo testnet changes

_data/chains/eip155-50005.json, _data/chains/eip155-50006.json
We already occupied chainID 345 before but wanna change serial IDs with our mainnet and testnet.
=> change mainnet and add testnet of yooldo verse

_data/chains/eip155-912559.json, _data/icons/astria.json
Adds the devnet Astria EVM chain
=> Add Astria EVM Dusknet (912559)

_data/chains/eip155-42766.json
=> Add zkfair mainnet

_data/chains/eip155-1133.json, _data/icons/changi.json
I've updated some details about this entry (new RPC, different IPFS for icon, title). Please merge into main.
Thank you for your efforts!
=> Update DeFiMetaChain Changi Testnet (1133)

_data/chains/eip155-4078.json, _data/icons/muster.json
Adding Muster Chain (Arbitrum Orbit Appchain settling on Arbitrum One)
```
BUILD SUCCESSFUL in 5s
8 actionable tasks: 3 executed, 5 up-to-date
```
=> Add Muster chain

_data/chains/eip155-1890.json, _data/chains/eip155-1891.json
Provide load balanced RPC endpoints and also new link for Pegasus testnet faucet
=> Update LightLink network mainnet+testnet RPC's and faucet for testnet

_data/chains/eip155-103.json, _data/chains/eip155-10395.json
we want change symbol
please, confirm thankyou
=> Worldland network change symbol WL to WLC

_data/chains/eip155-879151.json, _data/icons/blx.json
=> Add BlocX Mainnet

_data/chains/eip155-1731313.json
This PR is ready for approval / merge. Thanks~
=> Update my TDD's RPC server address

_data/chains/eip155-11297108099.json, _data/chains/eip155-11297108109.json
* updated RPC & block explorers for Palm Testnet
* updated RPC & block explorers for Palm
Docs: https://docs.palm.io
=> Update Palm network

_data/chains/eip155-3799.json, _data/icons/tangle.json
This PR adds [Tangle Testnet](https://www.tangle.tools/) to the chainlist.
=> feat: add Tangle Testnet

_data/chains/eip155-32001.json, _data/icons/w3gamez.json
=> Add W3Gamez Network: Testnet

_data/chains/eip155-1100.json, _data/icons/dymension.json
* removed `incubating` status
* added explorer
* added icon
=> Update Dymension chain

_data/chains/eip155-499.json, _data/chains/eip155-799.json
I've updated the url for the rupaya website and added testnet chain particulars
=> Add Rupaya Testnet and Update Website URL

_data/chains/eip155-4653.json, _data/icons/gold.json
=> add Gold chain

_data/chains/eip155-1953.json, _data/chains/eip155-1961.json, _data/icons/selendra.json
Selendra aims to be a smart contract network for developers and enterprises in Cambodia and Southeast Asia. It supports Ethereum Virtual Machine (EVM) and WebAssembly (Wasm) with a Proof-of-Stake consensus. 
Block explorer is still in development.
=> Add Selendra Network 

_data/chains/eip155-274.json
- Update features attribute to include EIP1559
=> Update features info for chain 274

_data/chains/eip155-7700.json
- remove defunct canto RPCs
- add new canto RPC
- update block explorers
=> update canto RPCs, explorers

_data/chains/eip155-570.json, _data/chains/eip155-57000.json
For reference: https://support.syscoin.org/t/pollums-infra-reports-dec-jan/761
=> Add Pollum RPCs for Syscoin NEVM and Syscoin Rollux testnets

_data/chains/eip155-52014.json, _data/chains/eip155-5201420.json
Change the RPC URL for the mainnet and testnet.
=> Change RPCs for Electroneum Mainnet & Testnet

_data/chains/eip155-5102.json
This PR adds SIC testnet chain
=> Add sic testnet

_data/chains/eip155-1729.json
Added Reya Network.
Web site: https://reya.xyz/
Info: https://raas.gelato.network/rollups/details/public/reya-network
=> Reya Network configuration

_data/chains/eip155-8890.json
=> update RPC Link

_data/chains/eip155-8822.json, _data/icons/iotaevm.json
Added the new chain of IOTA EVM
=> Added new chain of IOTA EVM

_data/chains/eip155-77787778.json
=> Adding 0xHash Testnet

_data/chains/eip155-145.json
=> Add Sora Testnet

_data/chains/eip155-138.json
<h1 dir="auto">Decentralized Currency Hybrid Blockchain: Uniting Diverse Financial Systems</h1>
<h2 dir="auto">Introduction</h2>
<p dir="auto">This pull request is a significant step forward in the evolution of blockchain technology. We are introducing the <strong>Defi Oracle Meta Mainnet</strong>, a hybrid blockchain system that not only unifies public, permissioned, and private blockchains but also brings a host of new features to enhance user experience and system functionality.</p>
<h2 dir="auto">Key Features</h2>
<ol dir="auto">
<li><strong>Hybrid Architecture</strong>: Integrating public, permissioned, and private components, our blockchain architecture offers unparalleled flexibility, ensuring high performance, robust security, and extensive scalability.</li> …
=> Updated the EIP-155-138 chain data file to include rpc and wss and explorer

_data/chains/eip155-202401.json
=> Add YMTECH-BESU Testnet

_data/chains/eip155-5439.json
=> Add Egochain Network

_data/chains/eip155-5106.json
=> add Azra testnet

_data/chains/eip155-77001.json, _data/icons/bora.json
=> Add Borachain mainnet

_data/chains/eip155-60808.json
Adding the BOB mainnet configuration.
=> Add BOB mainnet chain id

_data/chains/eip155-555666.json
Please let me know if you need more info from us.
=> Add Eclipse Testnet

_data/chains/eip155-810181.json
- add zkLink Nova sepolia testnet: eip155-810181
=> add zkLink Nova sepolia testnet info

_data/chains/eip155-2121.json, _data/icons/catena.json
This pull request proposes the addition of the Catena Network to the chain list.  
Chain ID: 2121
Network name: Catena Network.
Please review and merge the changes.
Thanks
=> Add Catena Network Main Net

_data/chains/eip155-27181.json
Adding data for KLAOS Nova test chain
=> Adding data for KLAOS Nova

_data/chains/eip155-555666.json
Please let me know if you need more info from us.
Related PR: https://github.com/ethereum-lists/chains/pull/4819
=> Modify Native Token name on Eclipse Testnet

_data/chains/eip155-267.json
=> Update Neura testnet

_data/chains/eip155-1221.json, _data/icons/cycle.json
=> Add Cycle Network Testnet

_data/chains/eip155-4200.json
Add JSON RPC endpoint.
Update explorer name.
=> Update merlin mainnet info.

_data/chains/eip155-210049.json
Added new chain of GitAGI Atlas Testnet
=> Added new chain of GitAGI Atlas Testnet

_data/chains/eip155-103.json, _data/chains/eip155-10395.json
add rpc address && Edit capitalization
=> add_worldland_rpc&change_name

_data/chains/eip155-1073.json, _data/chains/eip155-1075.json, _data/chains/eip155-8822.json
Update info for IOTA EVM chain and ShimmerEVM chain
=> Update info for IOTA EVM chain and ShimmerEVM chain

_data/chains/eip155-28516.json
=> Add Vizing Testnet

_data/chains/eip155-1113.json, _data/chains/eip155-1123.json, _data/chains/eip155-223.json
Update B2 Mainnet and B2 Testnet
=> Update B2 Mainnet and B2 Testnet

_data/chains/eip155-302.json, _data/icons/zkcandy.json
Added zkCandy Sepolia Testnet chain.
=> Added zkCandy Sepolia Testnet.

_data/chains/eip155-5424.json
Please review our request, Thank you.
=> edeXa mainnet

_data/chains/eip155-60808.json, _data/icons/bob.json
- Adds BOB mainnet RPCs
- Adds BOB mainnet explorers
- Adds BOB logo
- Adds BOB L2 bridge
=> feat: add bob mainnet info

_data/chains/eip155-4048.json, _data/icons/gpu.json
Added json files for GAN tetsnet
=> Added Gan Testnet

_data/chains/eip155-979.json, _data/icons/sexyTestnet.json
Add EthXY Testnet
ChainID: 979
=> Add EthXY Testnet

_data/chains/eip155-37714555429.json, _data/chains/eip155-660279.json
=> Add Xai mainnet and testnet

_data/chains/eip155-39656.json, _data/chains/eip155-839320.json, _data/icons/prmIcon.json
https: primalnetwork.org
Primal Network Mainnet
Chain ID: 39656
RPC: https://mainnet-rpc.prmscan.org
Explorer: https://prmscan.org/
Primal Network Testnet
Chain ID: 839320
RPC: http://testnet-rpc.prmscan.org
Faucet: http://faucet.prmscan.org
Explorer: https://testnet-explorer.prmscan.org/
=> Adding new chain Primal Network Mainnet and Testnet

_data/chains/eip155-43111.json, _data/chains/eip155-743111.json, _data/icons/hemi.json
* Update testnet explorer url
* Add icon
=> Update Hemi info

_data/chains/eip155-111557560.json, _data/chains/eip155-7560.json, _data/icons/cyber.json
=> Update Cyber chain logo because of Cyber rebranding

_data/chains/eip155-969.json, _data/icons/sexy.json
Add EthXY Mainnet
ChainID: 969
=> Add EthXY Mainnet

_data/chains/eip155-599.json
=> Deprecate Metis Goerli Chain 599

_data/chains/eip155-12324.json, _data/chains/eip155-12325.json, _data/icons/l3x.json
=> Add L3X Protocol

_data/chains/eip155-98881.json
=> Add Ebi Chain

_data/chains/eip155-21224.json
**DCpay Testnet**
**Chain ID**: 21224
**Testnet RPC**: https://testnet-rpc.dcpay.io
**Testnet Explorer**: https://testnet.dcpay.io
**Faucet**: https://faucet.dcpay.io
=> Added DCpay testnet eip155-21224.json file

_data/chains/eip155-8329.json, _data/icons/lorenzo.json
Add eip155-8329.json for my public chain
Main website: https://www.lorenzo-protocol.xyz/
Chain ID: 8329
Explorer: https://scan.lorenzo-protocol.xyz/
=> feat: add lorenzo mainnet info

processor/src/main/kotlin/org/ethereum/lists/chains/Main.kt, processor/src/main/kotlin/org/ethereum/lists/chains/model/Exceptions.kt
Can prevent me a click in some review cases
=> Check if explorers return 200

_data/chains/eip155-6322.json
Create a PR to add Aura mainnet info.
Thanks!
=> add Aura mainnet

_data/chains/eip155-4061.json, _data/chains/eip155-4062.json, _data/chains/eip155-5551.json, _data/chains/eip155-5553.json
Update chain specs. for nahmii networks.
=> update nahmii chains

_data/chains/eip155-10849.json, _data/chains/eip155-10850.json, _data/chains/eip155-764984.json, _data/chains/eip155-767368.json
Add Lamina1, Lamina1 Identity, Lamina1 Testnet, and Lamina1 Identity Testnet chains
=> Add Lamina1 chains

_data/chains/eip155-4488.json, _data/chains/eip155-8844.json, _data/icons/hydra.json
Proposal to add Hydra Chain and Hydra Chain Testnet information.
Thanks in advance!
=> Add hydra chain and hydra chain testnet

_data/chains/eip155-200810.json
update Bitlayer testnet scan url and standard
=> update Bitlayer testnet scan url and standard

_data/chains/eip155-83872.json, _data/icons/zedx.json
This commit updates Zedxion network native currency symbol and also adds icon for zedx.
=> Update Zedxion network & add zedx icon

processor/src/main/kotlin/org/ethereum/lists/chains/model/Exceptions.kt
Although URLs begin with U, in most cases, it is customary to use the article a
=> chore: correct the use of article

_data/chains/eip155-2777.json
Update rpc and explorer for GM Network Mainnet (already launched)
RPC: https://rpc.gmnetwork.ai
Explorer: https://scan.gmnetwork.ai
=> Update rpc and explorer for GM Network Mainnet

_data/chains/eip155-9981.json, _data/icons/volley.json
=> Add Volley Mainnet

_data/chains/eip155-53302.json, _data/icons/seedTestnet.json
ℹ️ Superseed Sepolia Testnet Info:
- **Website:** https://www.superseed.xyz/
- **Docs:** https://docs.superseed.xyz/
- **Explorer:** https://sepolia-explorer.superseed.xyz/
=> Add Superseed Sepolia Testnet

_data/chains/eip155-1328.json
=> Add Sei testnet

_data/chains/eip155-656476.json, _data/icons/open-campus-codex.json
Adds the Open Campus Codex Network
=> Add Open Campus Codex Network

_data/chains/eip155-1123.json, _data/chains/eip155-223.json
update B2 mainnet and testnet rpc
=> update B2 mainnet and testnet rpc

_data/chains/eip155-3639.json, _data/chains/eip155-3645.json, _data/icons/iChain.json
Add iChain Testnet, and Logo for mainnet and testnet
=> Add iChain Testnet

_data/chains/eip155-80084.json
=> Update Berachain bArtio rpc

_data/chains/eip155-490000.json
Adds Autonomys Testnet Nova EVM domain
=> Add Autonomys Testnet Nova Domain (490000)

_data/chains/eip155-360.json
This PR adds Shape to the list of registered chains. Shape mainnet will be launching within the next few months.
=> Add Shape mainnet definition

_data/chains/eip155-480.json
This PR adds World Chain to the list of registered chains.
=> Add World Chain

_data/chains/eip155-852.json
We are initiating the establishment of a Hong Kong blockchain, which is based on local Hong Kong enterprises and develops blockchain applications in the fields of games and finance, The ID of this chain is 852, and the network ID is also 852. This time we submitted one files : eip155-852.json . Please help check whether it meets the requirements, thank you!
=> We are initiating the establishment of a Hong Kong blockchain

_data/chains/eip155-413413.json
=> Update symbol AIE Chain

_data/chains/eip155-48900.json
Adds the Zircuit Mainnet Network configuration
=> Add Zircuit Mainnet

_data/chains/eip155-484752.json
This PR adds World Chain Sepolia to the chain registry.
=> Add World Chain Sepolia

_data/chains/eip155-1456.json, _data/chains/eip155-1789.json
=> Add ZKBase Mainnet

_data/chains/eip155-3338.json, _data/icons/peaq.json
- Added icon spec
- Added chain spec
=> Add peaq Network

_data/chains/eip155-75512.json, _data/chains/eip155-75513.json
GEEK chain native currency has been changed to OAS
=> [75512][change] GEEK chain native currency

_data/chains/eip155-1223.json
add cycle testnet jellyfish with chain id 1223.
@ligi would you please help to review this pull request
=> add cycle testnet jellyfish

_data/chains/eip155-77677.json
add cycle mainnet sailboat with chain id 77677
@ligi would you please help to check this pull request, thanks
=> add cycle mainnet sailboat

_data/chains/eip155-2425.json
We upgraded our chain from testnet to mainnet. Please take a look.
=> Update King Of Legends Chain Info

_data/chains/eip155-47763.json
Neo X was launched today.
https://medium.com/neo-smart-economy/neo-x-mainnet-launches-f524ab7afeb6
This PR just adds the mainnet chain info.
=> Add Neo X Mainnet

_data/chains/eip155-164.json
Updates Omni.Network testnet name to "Omega"
=> Updates Omni Testnet to Omega

_data/chains/eip155-8333.json
Adding B3 Mainnet to Chainslist!
=> Add B3 Mainnet

_data/chains/eip155-808813.json
=> add bob sepolia

_data/chains/eip155-93747.json
=> add StratoVM testnet

_data/chains/eip155-123420000220.json
=> Add Fluence Stage (testnet)

_data/chains/eip155-81.json
Hi, 
I added RPC for the Japan Open Chain Mainnet.
Thank you for reviewing!
=> Update rpc for Japan Open Chain Mainnet

_data/chains/eip155-10081.json
Hi,
I added RPC for the Japan Open Chain Testnet.
Thank you for reviewing!
=> Update rpc for Japan Open Chain Testnet

_data/chains/eip155-229772.json, _data/icons/abyss.json
Adding our Testnet to the list.
=> Add AbyssProtocol Testnet

_data/chains/eip155-6678.json, _data/icons/emc.json
add EdgaMatrix Chain; 
BUILD SUCCESSFUL in 18s
6 actionable tasks: 1 executed, 5 up-to-date
npx prettier --write _data/*/*.json  format json success;
=> add EdgaMatrix Chain

_data/chains/eip155-55614.json
=> Flamma Mainnet

_data/chains/eip155-16166.json, _data/icons/cypherium.json
Adding Cypherium to the chain list. I added an icon entry as well.
=> Adding Cypherium to the chain list

_data/chains/eip155-54321.json, _data/chains/eip155-77777.json
- Updated Native currency for Toronet mainnet and testnet
- Updated RPC for Toronet mainnet
=> - Updated RPC for Toronet mainnet

_data/chains/eip155-6678.json, _data/chains/eip155-99876.json
BUILD SUCCESSFUL in 12s
6 actionable tasks: 1 executed, 5 up-to-date
npx prettier --write _data/*/*.json success
=> update 99876 chain's name and 6678 chain's name

_data/chains/eip155-52164803.json
=> Add Fluence Testnet

_data/chains/eip155-9999999.json
=> Add Fluence (mainnet)

_data/chains/eip155-1228.json
Registration of Cycle testnet Cuttlefish
=> Add Cycle testnet Cuttlefish

_data/chains/eip155-545.json, _data/chains/eip155-747.json
Flow network names were incorrect
=> Correct naming of Flow networks

_data/chains/eip155-102030.json
This PR should ideally be merged soon after the new mainnet launches, 2024-08-28 10am EST.
=> Adding Creditcoin 3 Mainnet Chain

_data/chains/eip155-1414.json, _data/chains/eip155-1722641160.json, _data/chains/eip155-2355.json
* Change status to active
* Credible urls updated. (rpc, explorer, bridge, info)
* Unfortunately, the chainId of the final working testnet has been changed.
* Mark deprecated, previous testnet json.
* New testnet json file, added.
=> Update mainnet / testnet info

_data/chains/eip155-68775.json
Mainnet has already been added and Testnet will be using the same icon.
https://github.com/ethereum-lists/chains/pull/3623
=> Add dm2verse Testnet.

_data/chains/eip155-480.json, _data/chains/eip155-4801.json
This PR adds public RPC endpoints for World Chain and World Chain Sepolia.
=> Add rpc urls for World Chain and World Chain Sepolia

_data/chains/eip155-281123.json
=> add athene parthenon

_data/chains/eip155-1953.json, _data/chains/eip155-1961.json
RPC update. Request update on Chainlist
=> Update rpc for Selendra

_data/chains/eip155-8108.json, _data/chains/eip155-8408.json, _data/icons/zenchain.json
This PR adds the Zenchain Testnet network to the chain list. Thank you!
=> Add Zenchain Testnet and Mainnet to list

_data/chains/eip155-766.json
The Update link to the explorer for the QL1 network.
=> Updated the QL1 Mainnet explorer link

_data/chains/eip155-183.json
Update of Ethernity mainnet name
=> Ethernity chain name changed

_data/chains/eip155-9302.json
Adding the Galactica Network TestNet:
[https://docs.galactica.com/galactica-developer-documentation/testnet-reticulum](https://docs.galactica.com/galactica-developer-documentation/testnet-reticulum)
Official Website:
[https://galactica.com/](https://galactica.com/)
=> feat: add galactica reticulum (testnet)

_data/chains/eip155-41923.json, _data/icons/occ-mainnet.json, _data/iconsDownload/QmAbz7VfGvf6NVHezuBy5HpJTCi1gEshBxxdDdfVXNQ8Bt
I would like to add Open Campus Codex Mainnet.
=> Add Open Campus Codex Mainnet

_data/chains/eip155-1398243.json, _data/chains/eip155-65536.json
1. Update rpc and explorer link of Automata Testnet
2. Add rpc and explorer link of Automata Mainnet
=> Update info of Automata Mainnet and Testnet

_data/chains/eip155-8822.json
See https://wiki.iota.org/build/networks-endpoints/#iota-evm
=> Fix rpc for iota evm

_data/chains/eip155-46.json
related: https://github.com/ringecosystem/integration/issues/16
=> Add new rpc for darwinia

_data/chains/eip155-10025.json, _data/icons/aeon.json
This PR adds AeonChain mainnet (Chain ID:10025)
=> add aeon chain

_data/chains/eip155-2710.json, _data/chains/eip155-2818.json
=> Add Morph mainnet

_data/chains/eip155-2478899481.json
Adds [Accumulate Kermit Testnet](https://kermit.explorer.accumulatenetwork.io/)
=> Accumulate Kermit

_data/chains/eip155-480.json, _data/chains/eip155-4801.json
Adds additional RPC providers, block explorers, and parent chain info for World Chain Mainnet and Sepolia. Updates infoURL for World Chain Mainnet and Sepolia. Updates status for World Chain Mainnet. Adds faucets for World Chain Sepolia.
=> feat: update World Chain info

_data/chains/eip155-279.json, _data/iconsDownload/bafkreiatcu42wbjlo24mr35jou4awvsqpaqys6iv4kxgkjhno3haovsiaq
- Update RPCs
- Add official block explorer
- Add logo file
- Update other metadata
=> Update BPX Chain

_data/chains/eip155-16604737732183.json, _data/chains/eip155-253368190.json, _data/icons/flame.json
=> Add Flame chains

_data/chains/eip155-272247.json, _data/chains/eip155-272520.json, _data/icons/nxy.json
thank you for ALL of your efforts :pray: 
will :100: donate again!
=> Add Nxy Mainnet (The Oasis) + Testnet (Area 51) to Chainlist.

_data/chains/eip155-1998991.json, _data/icons/xphere.json
Request PR to add Xphere testnet.
=> Add Xphere testnet

_data/chains/eip155-1686.json
=> Update Mint Testnet Status

_data/chains/eip155-763373.json
=> Add Ink Sepolia

_data/chains/eip155-28882.json
- Fixed L2 parent from Mainnet to Sepolia
- Removed mainnet bridge
=> Fix Boba Sepolia

_data/chains/eip155-1829.json
=> Add Playblock (eip155-1829)

_data/chains/eip155-10143.json, _data/chains/eip155-143.json, _data/chains/eip155-20143.json, _data/icons/monad.json
Currently the fields left blank are TBD (RPC, explorer, faucet).
=> add monad devnet, testnet and mainnet

_data/chains/eip155-11155420.json, _data/chains/eip155-421614.json, _data/chains/eip155-43113.json, _data/chains/eip155-43114.json, _data/chains/eip155-80002.json, _data/chains/eip155-8453.json, _data/chains/eip155-84532.json
* Add polygonscan-amoy
* Add basescan-sepolia
* Add etherscan-sepolia-optimism
* Add arbiscan-sepolia
* Add snowscan and snowscan-testnet
=> Add and update some Etherscan explorers

_data/chains/eip155-59141.json
Linea Sepolia settles to Sepolia, not Goerli
=> Fix linea sepolia parent

_data/chains/eip155-5330.json, _data/icons/superseed.json
ℹ️ Superseed Info:
- **Website:** https://www.superseed.xyz/
- **Docs:** https://docs.superseed.xyz/
- **Explorer:** https://explorer.superseed.xyz/
=> Add Superseed Mainnet

_data/chains/eip155-4321.json
Adds chain info for echos mainnet
=> Add Echos Mainnet

_data/chains/eip155-1946.json
=> Fix Soneium minato parent

_data/chains/eip155-88866.json, _data/icons/matr1x.json
=> add# matr1x testnet

_data/chains/eip155-37111.json, _data/icons/lens.json
[Network Details](https://dev-preview.lens.xyz/docs/network/using-lens-network)
[Icon](https://x.com/lensprotocol)
=> feat: update lens testnet

_data/chains/eip155-9091.json
I need to update RPC URLs, Faucet & Info URL for KPA Smart Chain Testnet
=> Update eip155-9091.json for RPC URLs, Faucet & Info URL

_data/chains/eip155-88899.json, _data/chains/eip155-888991.json
adding mainnet and testnet definitions
=> incubating UNITE

_data/chains/eip155-21000001.json
- add corn testnet
- add L2 parent to corn mainnet
=> Add Corn testnet

_data/chains/eip155-44474237230.json, _data/icons/deriw.json
This PR adds the Deriw Devnet chain in the chainlist (eip155-44474237230.json).
=> Add Deriw devnet

_data/chains/eip155-75338.json
This PR adds the AppLayer Testnet chain in the chainlist (`eip155-75338.json`).
=> Add AppLayer Testnet Chain

_data/chains/eip155-824.json, _data/chains/eip155-825.json, _data/icons/daily.json
Adding Daily Network testnet and mainnet
=> Add Daily Network

_data/chains/eip155-325.json, _data/chains/eip155-326.json
Our exchange has launched on mainnet and testnet, and this PR is to update the name as well as the rpc endpoints to avoid metamask complaining about missing mismatches
For your reference this is the original PR to add these 2 chains https://github.com/ethereum-lists/chains/pull/5227
Thank you in advance!
=> Update GRVT mainnet/testnet chain information

_data/chains/eip155-43521.json, _data/icons/memecore.json
This is our public testnet info.
We will launch mainnet soon.
=> Add MemeCore Chain Formicarium Testnet

_data/chains/eip155-440017.json, _data/chains/eip155-54170.json, _data/icons/graphite.json
Add Graphite Mainnet (chain id 440017) and Graphite Testnet (chain id 54170)
=> add Graphite Chain

_data/chains/eip155-240240.json, _data/icons/studio.json
- Added Studio Testnet (chainId: 240240)
- Added Studio icon
- Validated with gradle tests
=> Add Studio Testnet chain and icon

.github/workflows/pr_checks.yml
The original name is wrong and misleading for debugging
=> Fix pr_checks action step name

_data/chains/eip155-4284265.json, _data/icons/zuuxchain.json
=> Added eip155-4284265

_data/chains/eip155-57073.json
Adding in rpcs, faucet, and explorer information
=> Ink Mainnet network Information

_data/chains/eip155-3939.json
Please update my testnet name, it syntax error! thank you very much!
=> update name testnet. Thank

_data/chains/eip155-1514.json
Update mainnet info for Story Network.
=> [feat] add story mainnet

_data/chains/eip155-12323.json, _data/icons/huddle01.json
=> Add Huddle01 chain

_data/chains/eip155-91111.json, _data/icons/henez.json
=> Add Henez chain

_data/chains/eip155-550.json
Updating the InfoURL and shortname
=> Update River infoURL

_data/chains/eip155-3969.json, _data/icons/paynetwork.json
=> Add PayNetwork chain

_data/chains/eip155-82614.json, _data/icons/vemp-horizon.json
=> Add vemp horizon chain

_data/chains/eip155-7865.json, _data/icons/power.json
=> Add Powerloom Mainnet

_data/chains/eip155-4913.json, _data/icons/oev-network.json
=> Add OEV chain

_data/chains/eip155-753.json, _data/icons/rivalz.json
=> Add rivalz chain

_data/chains/eip155-14235.json, _data/icons/bitlazer.json
=> Add bitlazer chain

_data/chains/eip155-4488.json
The PR includes the activation of the HydraChain Mainnet network
=> Activate Hydra Mainnet and update URLs

_data/chains/eip155-10081.json, _data/icons/joct.json
Hi ethereum-lists team,
I'm a developer of the Japan Open Chain team. I've created PR to submit our chain: https://github.com/ethereum-lists/chains/pull/3310. Now, we're changing the logo.
Thanks for your support.
=> feat: Add Japan Open Chain Testnet icon

_data/icons/story.json
**CONTEXT**
We'd like to update token icon design per request from our design team. The ipfs link has been updated, and it can be validated with this link: https://ipfs.io/ipfs/bafkreierdbo6kxvq5l353dqzg5qkaennz5s6hjp3nvmvyz2dx7gfka4nuu
=> [feat] update token icon design

README.md
A performant Next.js based virtualised tabular view of chains.json file. Hosted on Vercel for best load times, high uptime, reliability & TTFB.
Features include - 
1) Connecting wallet using Rainbowkit & Adding Chains
2) Searching Chains via Name, ID or Shortname
3) Virtualised tabular view for improved performance and no search stutter or heavy resource usage due to entire listing on the DOM.
4) Debounced Search input
5) Clean interface yet all information accessible on single screen.
=> Add new listing site - Chainlist.simplr.sh - Information dense single pager.

_data/chains/eip155-26988.json
Please have a review and approval the workflows.
=> add Newton Finance Testnet

_data/chains/eip155-1946.json
This PR aligns naming to OP Superchain registry
=> Rename Minato network to Soneium Minato

_data/chains/eip155-678.json, _data/chains/eip155-679.json, _data/icons/janction.json
added mainnet, testnet and icon
=> added Janction networks

_data/chains/eip155-175190.json
This adds Chronicle Loa, our new Lit Protocol testnet
=> add chronicle loa - lit testnet

_data/chains/eip155-161201.json, _data/icons/openledger.json
This PR is focused on adding a new chain openledger testnet to the configuration.
=> openledger testnet chain config added

_data/chains/eip155-1868.json
Soneium mainnet - change status to active and update relevant links
=> Update Soneium info

_data/chains/eip155-80931.json, _data/icons/forta-chain.json
=> add Forta Chain

_data/chains/eip155-490092.json
I have added PumpFi Chain Testnet
=> Pumpfi Chain Testnet

_data/chains/eip155-5371.json, _data/chains/eip155-5372.json, _data/chains/eip155-5373.json
As we announced the launch of the Settlus Sepolia Testnet, we’ve updated information about Settlus.
=> update settlus info

_data/chains/eip155-9003.json, _data/icons/qubetics.json
qubetics testnet configuration added.
=> add qubetics testnet

_data/chains/eip155-224400.json
CONET DePIN Main Network
Layer Minus Protocol
Wallet to Wallet Information and Communication
=> Add CONET Mainnet Chain (224433)

_data/chains/eip155-1278060416.json, _data/icons/vasyl.json
I have added OFFICIAL VASYL TESTNET eip155-1278060416.json and icon vasyl.json
=> added official vasyl chain

_data/chains/eip155-1278060416.json
I have corrected the chain name and title to OFFICIAL VASYL
=> corrected chain name for official vasyl

_data/chains/eip155-1.json
Update `eip155-1.json` to add [api.securerpc.com/v1](https://api.securerpc.com/v1) for RPC gateway.
This gateway provides MEV complete privacy, as well as MEV Relay connection directly. It has been in operation since 2020
=> feat(eip-155-1): add securerpc

_data/chains/eip155-6231991.json
Created a new branch with the same name from:
https://github.com/ethereum-lists/chains/pull/6730
=> add chainId 6231991 name Block Chain LOL Berachain Testnet

_data/chains/eip155-1702448187.json, _data/icons/witness.json
=> Added Witness Chain

_data/chains/eip155-96737205180.json, _data/icons/aldrickb.json
* Add AldChain testnet definition
=> Add AldChain testnet definition

_data/chains/eip155-1995.json
=> updated edeXa RPC

_data/chains/eip155-6900.json, _data/chains/eip155-7210.json, _data/chains/eip155-7222.json
=> chore: update nibi names to be compatible with webapp

_data/chains/eip155-10218.json, _data/chains/eip155-6122.json
Reservations for upcoming Tea Test/Mainnets
=> add Tea main- and testnets

_data/chains/eip155-2340.json, _data/chains/eip155-2440.json
added Atleta mainnet chainID:2440, also added new RPCs for Atleta Olympia id2340
=> chore: added atleta mainnet 2440, added new rpcs for atleta olympia

_data/chains/eip155-1953.json, _data/chains/eip155-1961.json
Update explorers url for Selendra Network.
EVM explorer by Blockscout
=> Update explorers to https://explorer.selendra.org

_data/chains/eip155-1698369.json, _data/chains/eip155-698369.json
Added Primea Chain Testnet ID 1698369
Modified Primea Chain name to Primea Chain Mainnet
=> Added Primea Chain ID Testnet 1698369

_data/chains/eip155-210.json
=> update btn info

_data/chains/eip155-331.json, _data/icons/telos.json, _data/icons/teloscan.json
Adding Telos zkEVM Testnet 
```
BUILD SUCCESSFUL in 25s
6 actionable tasks: 6 executed
```
=> Add Telos zkEVM Testnet - chainid : 331

_data/chains/eip155-45003.json, _data/icons/juneomainnet.json
New files added : 
- Juneo mainnet chain information
- Juneo logo
=> Add Juneo mainnet chain information and logo

_data/chains/eip155-1660990954.json, _data/icons/sn.json
Hello team!
Doing this PR to add Status Network Sepolia Testnet.
Status Network is an L2 built with the Linea stack anchored to Ethereum as the L1
You can find more info here: https://status.network
We followed the guide and the maintainer checklist so hopefully all is good!
Many thanks,
the Status Network team
=> Add Status Network Sepolia - chainId: 1660990954

_data/chains/eip155-212013.json
=> Update heima endpoints

_data/chains/eip155-52014.json, _data/chains/eip155-5201420.json
Update our RPCs, add a faucet to the testnet and update the testnet explorer URL.
=> Modify electroneum networks

_data/chains/eip155-695569.json, _data/chains/eip155-80069.json, _data/icons/pyrope.json
=> Add Pyrope Testnet

_data/chains/eip155-295.json
Added LinkPool's archive Hedera mainnet node.
=> Add LinkPool Hedera mainnet node

_data/chains/eip155-101003.json, _data/icons/juneoSocotraTestnet.json
* add juneo Socotra testnet chain details and logo
=> Add Juneo Socotra testnet chain information and logo

_data/chains/eip155-45004.json, _data/chains/eip155-45005.json, _data/chains/eip155-45006.json, _data/chains/eip155-45007.json, _data/chains/eip155-45008.json, _data/chains/eip155-45009.json, _data/chains/eip155-45010.json, _data/chains/eip155-45011.json, _data/chains/eip155-45012.json, _data/chains/eip155-45013.json, _data/chains/eip155-45014.json, _data/icons/juneo-bch1.json, _data/icons/juneo-dai1.json, _data/icons/juneo-doge1.json, _data/icons/juneo-eur1.json, _data/icons/juneo-gld1.json, _data/icons/juneo-link1.json, _data/icons/juneo-ltc1.json, _data/icons/juneo-mbtc1.json, _data/icons/juneo-sgd1.json, _data/icons/juneo-usd1.json, _data/icons/juneo-usdt1.json
Patch : Add all chains from Juneo Primary Supernet with definitions and icons
- Added definitions for each EVM-compatible chain
- Included corresponding icons for each chain
=> Patch : add all Juneo primary supernet chains

_data/chains/eip155-1200.json, _data/chains/eip155-1210.json, _data/chains/eip155-1868.json, _data/chains/eip155-210209.json, _data/chains/eip155-25839.json, _data/chains/eip155-272247.json, _data/chains/eip155-272520.json, _data/chains/eip155-31611.json, _data/chains/eip155-33139.json, _data/chains/eip155-3797.json, _data/chains/eip155-50312.json, _data/chains/eip155-70700.json, _data/chains/eip155-7208.json, _data/chains/eip155-72080.json, _data/icons/alveychain.json, _data/icons/apechain.json, _data/icons/cuckoo-ai.json, _data/icons/juneo-eur1.json, _data/icons/mezo.json, _data/icons/nexera.json, _data/icons/nxy.json, _data/icons/pop-apex.json, _data/icons/somnia.json, _data/icons/soneium.json, _data/icons/sorian.json, _data/icons/winr.json
=> Fix problems with some icons

_data/chains/eip155-428962654539583.json, _data/icons/yominet.json
=> Add Yominet network

_data/chains/eip155-1336.json, _data/icons/kii.json
Add KiiChain Testnet Oro to chain lists
=> Add Kii Testnet Oro to chain lists

_data/chains/eip155-129399.json
=> Add Tatara network

_data/chains/eip155-191919.json, _data/icons/altb.json
Pease have a review and approval the workflows.
=> Add Altblockscan Mainnet

_data/chains/eip155-69000.json
adding animechain mainnet with a chain id of 69000
=> Add Animechain Mainnet 

_data/chains/eip155-1071.json, _data/icons/ogpu.json
Added icon for Redbelly Testnet and Mainnet.
=> Add icon for Redbelly Network

_data/chains/eip155-5700.json
Ref.: https://github.com/ethereum/sourcify/pull/2050
=> Update URL of Syscoin Testnet Tanenbaum explorer (chain 5700)

_data/chains/eip155-1329.json
This PR adds `slip44` field to `_data/chains/eip155-1329.json`
=> feat: add sei slip44

_data/chains/eip155-98964.json, _data/icons/pay1.json, _data/icons/pay1scan.json
Added eip155-98964.json ,pay1scan.json and  pay1.json
=> Add pay1 chain

_data/chains/eip155-100610.json, _data/icons/monsoon.json
Monsoon is a Layer 1 blockchain build using the Avalanche.
=> feat: add Monsoon chain

_data/chains/eip155-5887.json, _data/icons/om.json
Add MANTRA Chain Testnet (chainId: 5887)
- Add configuration for MANTRA Chain Testnet
- Native currency: OM (18 decimals)
=> Add MANTRA Chain Testnet (5887) configurations with icons
