ethereum-lists/chains

chains.json
=> Rootstock spelling

_data/chains.json
Website: https://artis.eco
Block explorers: https://explorer.sigma1.artis.network/ http://explorer.tau1.artis.network/
chainIds: [246529](https://github.com/lab10-coop/sigma1/blob/1881ea80b475c10765d7a763ca6afd93df005b52/spec.json#L30) (sigma1) & [246785](https://github.com/lab10-coop/tau1/blob/master/spec.json#L30) (tau1) See also: https://github.com/satoshilabs/slips/pull/495
/cc: @d10r
=> Add ARTIS (ATS) sigma1 & tau1 networks

_data/chains.json
NetworkID |CHAIN_ID | Chain(s) | CMC registered
-- | -- | -- | --
1 | 1 | Ethereum mainnet | ✔
2 | 2 | Morden (disused) | -
3 | 3 | Ropsten | -
4 | 4 | Rinkeby | -
? | 30 | Rootstock mainnet | -
? | 31 | Rootstock testnet | -
? | 42 | Kovan | -
1 | 61 | Ethereum Classic mainnet | ✔
3 | 62 | Ethereum Classic testnet | -
1 | 2 | Expanse mainnet ([[1]], [[2]], [[3]]) | ✔
1 | 8 | Ubiq mainnet ([[2]] , [[3]]) | ✔
60 | 60 | GoChain | ✔
76 | 76 | Mix | -
88 | 88 | TomoChain | ✔
99 | 99 | POA Network | ✔
37129 | 101 | webchain | ✔
1 | 101 | EtherInc | ✔
64 | 64 | Ellaism | ✔
1 | 820 | Callisto mainnet ([[2]] , [[3]]) | ✔
11235813 | 1620 | Atheios | ✔
1987 | 1987 | EtherGem | ✔
1 | 31102 | EtherSocial Network | ✔
200625 | 200625 | Akaroma | ✔
1313114 | 1313114 | Ether-1 | ✔
7762959 |  7762959 | …
=> update Ethereum based off chains

README.md, _data/chains.json
=> Add Public RPC Endpoints

_data/chains.json
ThunderCore (ThunderCore.com) is an EVM compatible blockchain. It's testnet and mainnet are already live. We were redirected to this github page by the approver of this pull request: https://github.com/ethereum/EIPs/pull/1755 
Please merge these chainid changes to avoid any conflicts.
=> Add ThunderCore's chainids to the chainids list

_data/chains.json
Update RSK (formerly known as Rootstock) Mainnet and Testnet, chainId, networkId and rpc nodes.
=> Update RSK info

_data/chains/108.json, _data/chains/18.json
1. Use the shorter RPC-endpoint URL,
https://testnet-rpc.thundercore.com,
for Thundercore testnet.
2. Correct the Thundercore mainnet and testnet faucet URLs.
The old data was mistakenly listing the Thundercore testnet faucet as the mainnet one.
=> Update Thundercore faucets and testnet RPC URLs

_data/chains/28945486.json
Auxilium (AUX) is a cryptocurrency foundation of a philantropic company Auxilium Global. Its current main network started in summer of 2018, after performing swap from Sprouts blockchain and running a modified fork of Ethereum Go implementation.
Blockchain explorer is here: https://explore.auxilium.global
More information about Auxilium Global can be found here: https://auxilium.global
Gracias!
=> Adding Auxilium network

_data/chains/38.json
This is a request to add the Valorbit VAL network chain with the #38 . 
https://github.com/valorbit/go-ethereum/blob/release/1.9-val/params/config.go#L97
Thank you.
=> Add Valorbit (VAL) network chain (#38)

_data/chains/137.json, _data/chains/80001.json
- I've added two entries for listing [Matic network](https://matic.network) on `chainid.network`
- Matic Mainnet ( chainId: 137 )
- Matic Mumbai Testnet ( chainId: 80001 )
=> Matic network

_data/chains/1.json, _data/chains/100.json, _data/chains/3.json, _data/chains/4.json, _data/chains/42.json, _data/chains/56.json, _data/chains/77.json, _data/chains/97.json, _data/chains/99.json
(Those two BSC endpoints are shown as http:// on their website, but are in fact https:// only.)
=> Update/add RPC addresses including WebSocket URLs.

_data/chains/1313161554.json, _data/chains/1313161555.json
NEAR EVM behaves like Ethereum shard on NEAR and support set of tools like Truffle / Metamask, hence the chain-id requirement.
Details about NEAR EVM can be found in WIP spec: https://github.com/nearprotocol/NEPs/pull/106
The id for MainNet is hex("NEAR")
=> Adding NEAR EVM

_data/chains/1.json
ENS migrated to a new address a while ago. [0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e](https://etherscan.io/address/0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e) is the current ENS registry address.
* https://docs.ens.domains/ens-deployments
* https://docs.ens.domains/ens-migration/guide-for-dapp-developers
=> Update ENS registry address

_data/chains/8995.json
Add bloxberg blockchain. Bloxberg is a PoA AuRa EVM chain governed by research institutes with the goal of providing researchers with decentralized services. See bloxberg.org
=> Add Bloxberg (8995)

_data/chains/82.json
Adding the Meter mainnet chainID, which is set as 82 (0x52)
=> adding Meter mainnet chain id

_data/chains/1313161554.json, _data/chains/1313161555.json
Will add compatible ones later when they are live.
This is done per https://github.com/ethereum-lists/chains/pull/110#issuecomment-735820550 conversation
=> Remove RPC endpoints that are not Ethereum compatible

_data/chains/eip155-1313161556.json
This is a trivial follow-up to #110, which omitted the NEAR betanet.
Note that there are no faucets on the betanet, and none are needed as new account creation automatically funds the wallet with sufficient funds.
=> Add NEAR betanet to chain IDs

_data/chains/eip155-10.json, _data/chains/eip155-420.json
We're shipping a fresh chain to mainnet tomorrow & therefore have to change the chainID. I believe you suggested this when I submitted my first PR but we foolishly did not heed your advice. It seems 420 for mainnet was not meant to be.
Updated 420 to forever be our Goerli testnet & now 10 as the mainnet!
Thanks again for maintaining this repo @ligi 😊
=> Update Optimistic Ethereum ChainID for mainnet

_data/chains/eip155-420.json
These faucets are for goerli - but not for optimistic goerli as far as I see. Currently this leads to weird UX in WallETH as after you request funds from the faucet you do have them on the current chain:
Wondering if there are faucets for optimistic goerli currently
=> Remove faucets for optimistic goerli

_data/chains/eip155-1001.json, _data/chains/eip155-8217.json
Klaytn is an enterprise-grade, service-centric blockchain platform developed by
Ground X, the blockchain subsidiary of Korea's largest mobile platform Kakao.
Klaytn uses two chain IDs:
- 8217 for Klaytn Mainnet Cypress
- 1001 for Klaytn Testnet Baobab
=> Add ChainID for Klaytn

_data/chains/eip155-1666600000.json, _data/chains/eip155-1666600001.json, _data/chains/eip155-1666600002.json, _data/chains/eip155-1666600003.json
Harmony is evm-compatible and sharded blockchain where each shard can act as a individual ethereum-compatible chain. 
The chainIDs we reserved for the 4 shards in Harmony mainnets are:
shard 0: 1666600000
shard 1: 1666600001
shard 2: 1666600002
shard 3: 1666600003
=> add harmony mainnet chain IDs

_data/chains/eip155-40.json, _data/chains/eip155-41.json
Telos EVM is currently live on testnet and expected to deploy on the mainnet end of Q1 or early Q2.
=> Add Telos mainnet & testnet

_data/chains/eip155-33.json
GoodData is a machine learning based privacy protection platform.
This patch registers chainId: 33 (0x21) for GoodData Mainnet
=> Add ChainID for GoodData

_data/chains/eip155-8285.json
{
"name": "KorthoTest",
"chain": "Kortho",
"network": "Test",
"rpc": [
"https://www.krotho-test.net"
],
"faucets": [
],
"nativeCurrency": {
"name": "Kortho Test",
"symbol": "KTO",
"decimals": 11
},
"infoURL": "https://www.kortho.io/",
"shortName": "Kortho",
"chainId": 8285,
"networkId": 8285
}
=> Add chainID 8285 to KorthoTest

_data/chains/eip155-10000.json, _data/chains/eip155-10001.json
Hi, 
We are developing smartBCH, a sidechain of Bitcoin Cash which is compatible with EVM and Web3.
It's testnet is launching now, so we'd like to make a note about the chainid it uses.
You can learn more about our project at https://smartbch.org/ and https://docs.smartbch.org/
Thank you very much!
=> Add smartBCH

_data/chains/eip155-250.json
In previous PR did not look into the RPC values, at the moment only working public one is https://rpcapi.fantom.network, so that's the only one in the list now.
References to it:
https://ftmscan.com/apis#rpc
https://docs.fantom.foundation/tutorials/set-up-metamask
=> Fix on Fantom Public RPCs.

_data/chains/eip155-8080.json
GeneChain Adenine Testnet has been running for a while.
Here's the pull request to merge information for GeneChain adenine testnet.
Thanks!
=> Add GeneChain Adenine Testnet

_data/chains/eip155-1313161554.json, _data/chains/eip155-1313161555.json, _data/chains/eip155-1313161556.json
[EVM on NEAR](https://github.com/aurora-is-near/aurora-engine) is now called [Aurora](https://github.com/aurora-is-near), and has launched as of yesterday:
- https://near.org/blog/aurora-launches-near/
- https://aurora.dev
- https://doc.aurora.dev/develop/networks
=> Update the NEAR chains

_data/chains/eip155-80.json, _data/chains/eip155-8080.json
GeneChain mainnet is now ready for launching. The genesis block has been set to 2021/5/18 4:00 UTC.
Explorer is ensured the same version as our testnet. So it's EIP3091. Because the genesis block is in the future, only block 0 can be found on the scan at the moment.
Thanks for reviewing our pull request!
=> Add GeneChain mainnet

_data/chains/eip155-4689.json, _data/chains/eip155-4690.json
Update IoTeX chain's public RPC endpoints for mainnet and testnet.
Also adding faucet for testnet.
=> update IoTeX RPC and faucet

_data/chains/eip155-4.json
Update Rinkeby data with Etherscan URL: https://rinkeby.etherscan.io/
I was surprised that chains.json didn't has Rinkeby Etherscan URL, I almost started searching for a bug in my code
=> Add Rinkeby Etherscan

_data/chains/eip155-421611.json
* Added wss://rinkeby.arbitrum.io/ws to RPC Endpoints alongside the existing https one
* Added block explorer https://rinkeby-explorer.arbitrum.io
=> Arbitrum:Rinkeby - Added block explorer and websocket rpc endpoint

_data/chains/eip155-2559.json, _data/chains/eip155-8285.json
{
"name": "Kortho Mainnet",
"chain": "Kortho Chain",
"network": "mainnet",
"rpc": [
"https://www.kortho-chain.com"
],
"faucets": [
],
"nativeCurrency": {
"name": "KorthoChain",
"symbol": "KTO",
"decimals": 11
},
"infoURL": "https://www.kortho.io/",
"shortName": "Kortho",
"chainId": 2559,
"networkId": 2559
}
=> Add  ChainId 2559 for kortho mainnet

_data/chains/eip155-128.json
The infoURL seems to be an explorer URL rather than a URL for the information of the chain. <https://www.hecochain.com> was added back as it provides information of the chain.
=> HECO chain (128): Change infoURL to explorer URL. Fix infoURL.

_data/chains/eip155-137.json
The original RPC has been unusable for a long time and the has not been resolved, we should add new alternative URLs from the MATIC documentation(https://docs.matic.network/docs/develop/network-details/network/).
=> Add RPC URLs, and show the current name "Polygon"

_data/chains/eip155-32.json
GoodData is a machine learning based privacy protection platform.
This patch registers chainId 32 for GoodData Testnet.
=> Add ChainID for GoodData Testnet

_data/chains/eip155-777.json
cheapETH is alive and well and using chain ID 777!
Learn more at https://cheapeth.org, perhaps more legit than the Ethermint Testnet?
=> Add chain ID for the cheapETH blockchain

_data/chains/eip155-8.json
Announcement links:
* https://blog.ubiqsmart.com/announcing-gubiq-5-1-e4c5a9982073
* https://github.com/ubiq/UIPs/issues/9
=> Ubiq has switched Network ID to 8 to match Chain ID

_data/chains/eip155-200.json
Consider to add the information about Arbitrum on xDai rollup which is associated with the chain id 200.
=> Add information for Arbitrum on xDai

_data/chains/eip155-250.json
https://twitter.com/FantomFDN/status/1432824921613340680
Updating https://rpcapi.fantom.network
to https://rpc.ftm.tools
Signed-off-by: antonnell <antonnell.crypto@gmail.com>
=> Update Fantom RPC URL to https://rpc.ftm.tools

_data/icons/evmos.json
Adding `ipfs://QmU1avSagPdrjV7YuDc4faj5cjezrdNDjDTohLCyw7fPku` icon for evmos
=> docs: add evmos icon to ipfs

_data/chains/eip155-77.json
The official Sokol chain coin name is SPOA.
References:
https://www.poa.network/v/master-1/for-developers/getting-tokens-for-tests/sokol-testnet-faucet#interacting-with-spoa
https://blockscout.com/poa/sokol/
Chore:
- faucet link changed to https://faucet.poa.network
=> Change Sokol chain symbol SKL => SPOA

_data/chains/eip155-1287.json
This PR updates the rpc urls for the Moonbase Alpha TestNet 
https://docs.moonbeam.network/learn/platform/networks/moonbase/#network-endpoints
=> update rpc urls for Moonbase Alpha

_data/chains/eip155-666666.json, _data/chains/eip155-888888.json
eip155-666666  for vision vpioneer testnet ,already launched 
eip155-888888 for vision mainnet , will launch in 2022 H1
More detail:
Vision Native Currency VS decimal is 6 , but jrpc already compatible ,user use metamask send 1 (10**18) equal 1 vs (10**6)
https://www.visionscan.org/
https://developers.v.network/
=> vision network :add eip155-666666 eip155-888888

_data/chains/eip155-1313161554.json, _data/chains/eip155-1313161555.json
Add aurora's explorer urls for the Aurora Mainnet (1313161554) and TestNet (1313161555) chains.
=> adding explorer urls for aurora main/test chains

_data/chains/eip155-20.json
The rpc was no longer active, so updated this and the other chain info to https://api.elastos.io/eth, the faucet https://faucet.elastos.org/, and the explorer https://eth.elastos.io/
=> Updated Elastos RPC/Info

_data/chains/eip155-10.json, _data/chains/eip155-69.json
Hello! This is just a minor name change. Optimism has decided to call "Optimistic Ethereum" just "Optimism" from now on, since everyone was calling it that anyway. More context [here](https://optimismpbc.medium.com/to-optimism-4f01cc0eaa10).
=> fix: rename oe to optimism

_data/chains/eip155-1284.json, _data/chains/eip155-1285.json
Updates the RPC Endpoint for Moonriver. Also removes Blockscout as an explorer for Moonbeam
=> Updates RPC Information for Moonriver

_data/chains/eip155-10.json
Following up on conversation in https://github.com/ethereum-lists/chains/pull/203 – updating Optimism's currency symbol to keep in line with emerging standard across wallets & apps. 
cc @ligi
=> Update Optimism chain info

_data/chains/eip155-25.json
Inline with rename: https://medium.com/cronos-chain/cro-is-now-cronos-bf103c257bd
Details found here: https://cronos.org/docs/getting-started/metamask.html#connecting-to-the-cronos-mainnet-beta
=> Update Cronos name and URLs

_data/chains/eip155-1201.json
To make it easier to search our testnet on the Chainlist, we change name from "Avis Testnet" to "Evanesco Testnet".
=> Change "Avis Testnet" name to "Evanesco Testnet"

_data/chains/eip155-42161.json
Opening a PR to update the base currency symbol used in Arbitrum (for the same reasons as discussed in https://github.com/ethereum-lists/chains/pull/843)
=> Update Arbitrum chain info

_data/chains/eip155-9001.json
Current endpoint is broken, here's the working mainnet endpoint as well as an explorer url update.
=> Update evmos mainnet rpc and explorer

README.md
A few hours ago I forked Chainlist and set it up on chaindirectory.xyz. Will update the logo soon, already mentions credits to the original site.
Same code, open source, anyone can contribute with improvements.
If you agree, I think it makes sense to add it as Chainlist will no longer work after April 3.
=> Add ChainDirectory to readme

README.md
I forked chainlist repo and launched https://chain-list.org 
- `add to wallet` bugfix
- WalletConnect support (but some mobile wallet not support custom network)
- icons update for bsc, near, solana, evmos, harmony, etc.
- search debounce
- UI fix
=> Add chain-list.org to readme

_data/chains/eip155-1313161554.json, _data/chains/eip155-1313161555.json, _data/chains/eip155-1313161556.json
Aurora networks use ETH as the native currency to pay for gas so adding networks to MetaMask gave a warning because aETH is currently registered.
Update new explorer URLs.
=> Update Aurora explorer and symbol.

_data/chains/eip155-2001.json, _data/chains/eip155-200101.json, _data/icons/milkomeda.json
Add details for the [Milkomeda](https://dcspark.gitbook.io/milkomeda-getting-started/) C1 network to chainlist. Milkomeda C1 is an EVM-compatible L2 for Cardano.
=> add milkomeda

_data/chains/eip155-335.json, _data/chains/eip155-53935.json
The previous RPCs were removed by ava labs in support of this new DNS structure. Apologies for the extra PR
=> update dfk chain rpcs to new avax dns

README.md
I started using this repo's data in Otterscan to automatically discover the native currency name/symbol/decimals.
reference: https://twitter.com/wmitsuda/status/1509284311211679745
=> Add Otterscan to the usages section

_data/chains/eip155-11155111.json, _data/chains/eip155-3.json, _data/chains/eip155-4.json, _data/chains/eip155-42.json, _data/chains/eip155-5.json
This PR adds the network: "testnet" attribute to all known ethereum testnets.
There are other chains in the repository with this attribute, and potentially others not correctly flagged, this PR aims to fix this information only for ethereum chains.
My motivation to flag them is to properly filter them in my product (Otterscan), but I think other products can benefit of having this flag correctly set.
As an example, the chainlist fork of DefiLlama contains a "testnet" toggle in the UI and uses string parsing to guess the network is a testnet or not (see: https://github.com/DefiLlama/chainlist/blob/main/pages/index.js#L76).
=> Flag ropsten/rinkeby/kovan/goerli/sepolia as testnets

_data/chains/eip155-11297108099.json, _data/chains/eip155-11297108109.json
Fix Palm network RPC endpoints - use  proper string interpolation syntax: `${INFURA_API_KEY}`.
The invalid endpoints were added in #832,  thanks to @ptescher for pointing out the error.
=> Fix Palm RPC Endpoints

_data/chains/eip155-62621.json, _data/icons/multivac.json
I would be grateful if the MultiVAC chain could be added. The current explorer is custom, but a possible blockscout instance and integration with sourcify.eth in the near future.
=> Add eip155-62621.json for MultiVAC mainnet

_data/chains/eip155-42161.json, _data/chains/eip155-421611.json
The Arbitrum One free public endpoint no longer supports websockets, see
https://mobile.twitter.com/arbitrum/status/1530288743474659328
=> Remove free arbitrum one websocket endpoints

_data/chains/eip155-421611.json
Add `https://testnet.arbiscan.io` for the Arbiscan Rinkeby network (ChainID 421611).
=> Add Arbiscan Testnet explorer

_data/chains/eip155-6969.json
Tomb Chain is a Fast & Secure Layer 2 Optimistic Rollup running on top of Fantom Opera.
=> Add Tomb Chain (eip155-6969.json)

_data/chains/eip155-14.json
Flare Network has launched and is now in observation mode. The block explorer has been made publicly available. The native asset name has been determined to "FLR", same as the native asset symbol.
=> Update currency name and add block explorer

README.md
An "Add link to wallet" feature is available in Chainlink docs. see [here](https://docs.chain.link/docs/link-token-contracts/)
This feature uses this repo as reference data
=> Update README.md: Chainlink docs uses this reference data

_data/chains/eip155-32520.json
added the rpc.icecreamswap.com endpoint for the Bitgert (Brise) Blockchain.
=> added RPC endpoint for Bitgert

_data/chains/eip155-104.json, _data/icons/kaiba.json, _data/icons/kaibascan.json
As per https://kaibadefi.com , added KLC Testnet that will be followed shortly by KLC Mainnet (both will cohexists).
KLC is a gas-free EVM compatible QBFT blockchain with DAO based rewards and an active ecosystem spacing from ETH mainnet to KLC, gamefi and more
=> Added klc testnet (https://kaibadefi.com)

_data/chains/eip155-71401.json, _data/chains/eip155-71402.json
With the release of Godwoken Mainnet the RPC link is available. The previous URL for Godwoken Mainnet was a placeholder.
Also, fixing block explorer links for both Godwoken Testnet and Mainnet.
You can cross-check Mainnet RPC URL correctness by taking a look at this official nervosnetwork organization repository pull request: https://github.com/nervosnetwork/godwoken-info/pull/36 or here: https://docs.godwoken.io/connectionInfo
Also, pCKB is correct name for native token on Godwoken. It is different from CKB because CKB has 8 decimals, and pCKB has 18 decimals.
=> Update 71401 and 71402 details (Godwoken)

_data/chains/eip155-43114.json
Avalanche short name should not be "Avalanche", it shoud be "avax".
=> Avalanche short name incorrect

_data/chains/eip155-14.json
The native asset name for Flare Network has been changed to "Flare". Deprecated names include "Spark" and "FLR". 
The official documentation will reflect this change. Wallets and exchanges listing Flare Network's native asset should use the name "Flare" and the symbol "FLR".
=> Update Flare Network native asset name

_data/chains/eip155-137.json
Again, gnosis is leading the way with this standard so will open a few PRs to follow their shortNames.
https://gnosis-safe.io/app/matic:
=> Lowercase MATIC shortName to matic to adhere to https://eips.ethereum.org/EIPS/eip-3770

.gitignore, processor/src/main/kotlin/org/ethereum/lists/chains/Main.kt
As of now, we can list the chains using the data from the build but there was no way to list all the icons. 
This PR generates `chain_icons.json` and `chain_icons_mini.json` at the build time so we can list down all the icons that were defined in `_data/chains/eip155*.json`
=> Generate Icon list JSON in build

_data/chains/eip155-16.json
The native asset has been renamed from Spark to Flare, this also applies to the test network Coston. Also see https://flare.xyz/update-for-exchanges/
=> Update currency name

_data/chains/eip155-11111.json
This PR updates a few out of date URLs for the WAGMI network. If you check the URLs, you can see that all of the old URLs redirect to the new replacements.
=> Update URLs for WAGMI

_data/chains/eip155-8080.json
Shardeum 1.3 is down and shardeum 1.4 is now replaced on it with the same rpc, explorer urls and chainID.
=> fix: shardeum 1.3 is down and now replaced with shardeum 1.4

_data/chains/eip155-75000.json
the old .ml is legacy and is not working already. i need to change it to dev
=> change .ml TLD to .dev

_data/chains/eip155-7700.json
Change CANTO (chainId 7700) RPC from `https://canto.evm.chandrastation.com` to `https://canto.slingshot.finance` as the previous one only contains a partial state of the chain.
This is causing downstream errors in sourcify smart contract verification
Block queries below done using cast from foundry (https://github.com/foundry-rs/foundry):
=> update canto rpc

_data/chains/eip155-2002.json
This adds the mainnet config for the Milkomeda A1 deployment (testnet configs were previously merged [here](https://github.com/ethereum-lists/chains/pull/1429))
=> Add Milkomeda A1 configs

_data/chains/eip155-336.json
Specified _https_ endpoint for Shiden network is not available and seems to be replaced. 
That PR reflects those changes, and update public RPC endpoints to correspond to those described on their web page (https://docs.astar.network/docs/quickstart/endpoints)
=> Update rpc endpoint - Shiden (Evm) 

_data/chains/eip155-31415.json
Hi, I've just added one more explorer for Filecoin wallaby network
Example of work using `EIP3091` standard:
https://explorer.glif.io/wallaby/address/0xF1610892C3762C8bBb42b33203e9aD8B37A5c45d/
=> add Glif Explorer as Filecoin Wallaby explorer

_data/chains/eip155-2151.json, _data/icons/agora.json
We are public a new BOSagora mainnet in November.
Homepage: [https://bosagora.io](https://bosagora.io)
Blockexplorer : [https://boascan.io](https://boascan.io)
RPC: [https://mainnet.bosagora.org](https://mainnet.bosagora.org)
Docs: [https://docs.bosagora.org](https://docs.bosagora.org)
Could you please review it?
=> Add BOSagora mainnet eip155-2151

_data/chains/eip155-1234.json, _data/chains/eip155-12345.json, _data/icons/step.json
Step Network is EVM chain is powered by Avalanche subnet technology. Based on the [Avalanche](https://avax.network/) node with step [subnet](https://docs.avax.network/subnets) support baked in.
Could you please review it?
And thanks again for your amazing work guys.
=> Add STEP (FITFI) Main and Test networks

README.md
https://minerva.digital is using this list of chains
=> Add Minerva Wallet to Readme

_data/chains/eip155-45.json, _data/chains/eip155-46.json
Some part of the RPC info has been out-of-date. This pr fix that.
=> Update darwinia chains rpc endpoint

_data/chains/eip155-43114.json
I added the EIP1559 feature to the Avalanche chain, so that clients can correctly use type-2 transactions on Avalanche.
See also https://github.com/ethereum-lists/chains/issues/1901.
=> Avalanche (43114): Add EIP1559 feature

_data/chains/eip155-71401.json
As the Godwoken Testnet continues to evolve, we like to update a few info in the `eip155-71401.json` file:
1. Update the name of the chain to "Godwoken Testnet v1"
2. Add a new RPC URL "https://v1.testnet.godwoken.io/rpc"
To cross-check the new RPC URL and the name of the chain, please visit: 
- [README.md - godwoken-info](https://github.com/godwokenrises/godwoken-info/tree/main/testnet_v1_1#godwoken-web3-rpc)
- [Godwoken Public Networks - Godwoken Docs](https://docs.godwoken.io/connectionInfo#godwoken-testnet-v1)
=> Update 71401 (Godwoken Testnet v1)

_data/chains/eip155-500.json, _data/chains/eip155-501.json, _data/chains/eip155-502.json, _data/icons/camino.json
This PR adds both Camino (chainId 500, networkId 1000) and Columbus  (chainId 501, networkId 1001) networks. It also adds Camino logo.
=> Camino and columbus networks

_data/chains/eip155-13000.json
Hi team
The sps mainnet's rpc is migrated into following URI after incubation.
https://rpc.ssquad.games
Thanks
=> feat: add sps mainnet, chainId 13000

_data/chains/eip155-8080.json, _data/chains/eip155-8081.json
Liberty 2.0 is moving to Liberty 2.1.
This PR will make Liberty versions:
1.6 => 1.X
2.0 => 2.X
to avoid new PRs for Liberty version changes as requested here: 
https://github.com/ethereum-lists/chains/pull/1857#pullrequestreview-1179751038
=> Shardeum chainId 8080 and 8081 generic version numbers

_data/chains/eip155-8081.json
Adding RPC for chainId 8081 removed from:
https://github.com/ethereum-lists/chains/commit/87417e5e6de7a3e8ea76570e7c097f2b498e5850
=> rpc url for chainId 8081

.jitpack.yml
Otherwise klaxon 5.6 cannot be resolved
=> Tell jitpack to use openjdk 11

_data/chains/eip155-25925.json
- change it, because it's conflict with the Mainnet one
- BKC Testnet shortName will use "bkct" instead
=> Change BKC Testnet Shortname

_data/chains/eip155-42261.json, _data/chains/eip155-42262.json
Update Oasis Emerald name for consistency with Sapphire and the rest of the documentation.
=> Update Oasis Emerald name and info

_data/chains/eip155-56288.json, _data/chains/eip155-97288.json
eth_chainId is 0xdbe0 56288 for Boba BNB Mainnet
=> chainId fix for Boba BNB Mainnet

_data/chains/eip155-3141.json, _data/chains/eip155-31415.json, _data/chains/eip155-314159.json
EVM JSON RPC is only supported by the v1 Filecoin RPC, so we need to update the endpoint versions from v0
Also revising with direct links to faucet pages
=> Updating Filecoin RPC endpoint versions and direct faucet URLs

_data/chains/eip155-11155111.json
Makes it more consistent with the other testnets, such as goerli, which have ETH as symbol
=> Change sepolia's ether symbol

_data/chains/eip155-49088.json
Since this is a testnet, we add `t` to the shortname.
=> Fix The Bifrost Testnet Shortname

_data/chains/eip155-314.json, _data/chains/eip155-3141.json, _data/chains/eip155-314159.json
Changes:
- new Chainstack mainnet RPC added
- Filmine is rebranding to Dev.storage with new URL
- Filfox Calibration testnet explorer added at end of list per request of `ethereum-lists/chains` maintainers
https://github.com/ethereum-lists/chains/pull/2347 can also be closed in favor of this update.
=> Filecoin updates - new mainnet RPC, Filmine rebrand, Calibration testnet explorer update

_data/chains/eip155-1422.json, _data/chains/eip155-1442.json
Updates Polygon zkEVM Testnet according to [official docs](https://wiki.polygon.technology/docs/zkEVM/develop):
- Chain ID: 1442
Deprecated `1422` and added `1442`
=> Update Polygon zkEVM testnet (1442)

.github/workflows/pr_checks.yml
This adds a little automation to verify the basic image parameters if the PR adds or modifies icons.
Checks:
* ipfs should load (through cloudflare)
* width and height must match
* type should be one of png,jpg,svg and must match
Example of a good PR: https://github.com/farcaller/chains/pull/2
Example of a failing PR: https://github.com/farcaller/chains/pull/1
It is a slightly flaky test by nature as IPFS load might fail.
=> Add the image PR check

.github/workflows/pr_checks.yml, .github/workflows/prettier.yml
Reports the diff with changes instead of asking the user to run the tool: [example failure](https://github.com/farcaller/chains/actions/runs/4456330928/jobs/7826703319?pr=3).
It will also run on only the changed files since the previous check run.
Updated the original check to run only on the commits to master.
=> Add a slightly better linter check

.github/workflows/pr_checks.yml
This will prefer the cached copies of the icons if they are present in the PR. The remaining checks (dimensions and format) will still run.
Demo PR failure: https://github.com/farcaller/chains/actions/runs/4478054036/jobs/7870343997?pr=4
PS: I really need to rewrite this in js at this point. The amount of shell lines is getting a wee uncomfortable for human consumption 😄
=> Prefer cached icon copies over ipfs

_data/chains/eip155-740.json
it *is* https: https://testnet-explorer.canto.neobase.one
not having the `https` does not let users add this network to their metamask (for example)
=> fix canto testnet explorer url (http -> https)

_data/chains/eip155-500.json, _data/chains/eip155-501.json
Updates Columbus rpc to the correct one and changes infoURL for both Camino and Columbus networks.
=> Update Columbus and Camino rpc and infoURL

_data/chains/eip155-8080.json, _data/chains/eip155-8081.json, _data/chains/eip155-8082.json
Shardeum Explorer follows EIP-3091 URL routing now:
https://github.com/Shardeum/shardeum-bug-reporting/issues/40
=> Shardeum Explorer EIP-3091 standard support now

_data/chains/eip155-431140.json, _data/icons/markrgo.json
Hey,
Markr Go functions as a network abstraction platform that provides users with a seamless web3 experience, although it is not a blockchain in itself. 
As we described, our native currency currently is AVAX but subject to change.
Please note that: It's a launch preperation before we go live. When it's successfully merged, we are going to push the product.
Regards,
=> Add Markr Go Network

_data/chains/eip155-338.json
The Cronos Testnet block explorer URL has been changed to https://explorer.cronos.org/testnet. Update new this explorer URL in Chainlist.
=> Update Cronos Testnet Explorer URL

_data/chains/eip155-2124.json
Changed the metaplayerone dubai test network so it has a different name to the metaplayerone mainnet
=> Renamed metaplayerone dubai test network so has a different name to mainnet

_data/chains/eip155-534351.json, _data/chains/eip155-534353.json, _data/chains/eip155-534354.json
Established ChainId for in-development Scroll testnet on Sepolia.
Additionally, updates statuses to show that Scroll Alpha Testnet on Goerli is our only active network. PreAlpha has been deprecated, and mainnet is not yet active.
=> Add Scroll Sepolia (534351) & update other Scroll chains statuses

_data/chains/eip155-7777777.json
This PR adds network information for Zora's network, an optimistic rollup chain for zora.co.
More information is available at [zora.energy](https://zora.energy/).
=> Add ZORA chain mainnet

_data/chains/eip155-55004.json
This PR adds network information for Titan's network, an optimistic rollup chain.
More information is available at [tokamak.network](https://tokamak.network)
Thank you!
=> Add Titan chain mainnet

_data/chains/eip155-7777777.json, _data/icons/zora.json
This PR adds the icon for Zora's network, an optimistic rollup chain for zora.co.
More information is available at [zora.energy](https://zora.energy/).
=> feat: zora network icon

_data/chains/eip155-10.json
Renaming "Optimism" (Chain id: 10) to "OP Mainnet"
Official comms from Optimism FND: https://twitter.com/optimismFND/status/1672281032962478080
Optimism = Broader Ecosystem
OP Mainnet = Chain ID 10 Network
=> Rename Optimism (10) to OP Mainnet

_data/chains/eip155-61.json, _data/chains/eip155-63.json
Starting from July 24th, 2023 the current endpoints will be disabled, this PR updates them with the new ones listed in the announcement.
https://etccooperative.org/posts/2023-06-24-important-announcement-migrate-the-etc-and-mordor-rpc-endpoints-by-july-24-2023-en
=> Update Ethereum Classic RPC endpoints

_data/chains/eip155-9000.json, _data/chains/eip155-9001.json
Update Evmos config for mainnet and testnet:
- Block explorer link
- RPC provider
=> chore: update evmos config

_data/chains/eip155-56.json, _data/chains/eip155-97.json
**Summary**
Binance Chain has been rebranded into BNB Chain. This PR is to update the brand names and RPC URLs to the correct version. Refer to the [official BNB Chain documentation](https://docs.bnbchain.org/docs/rpc#bsc-mainnet-chainid-0x38-56-in-decimal).
**Changes**
- Update all `Binance Smart Chain` to `BNB Smart Chain`
- Update all `Binance Chain` to `BNB Chain`
- Update all RPC URLs domain from `binance` to `bnbchain`
- Update info URL to https://www.bnbchain.org/en
=> Update BNB Chain brand names

_data/chains/eip155-8453.json, _data/chains/eip155-84531.json, _data/icons/base.json, _data/icons/baseTestnet.json
Following up on [the testnet chain addition from @barmstrong](https://github.com/ethereum-lists/chains/pull/2318), we're excited to now add developer access for mainnet!
🔵 
--
> We’re excited to add Base, an Ethereum Layer 2 (L2) network offering a secure, low-cost, builder-friendly way for anyone, anywhere, to build decentralized apps onchain. Our goal with Base is to make onchain the next online and onboard 1B+ users into the cryptoeconomy. In pursuit of this goal, Base will serve as both a home for Coinbase’s onchain products, as well as an open ecosystem where anyone can build.
=> Adding Base mainnet (for builders)

_data/chains/eip155-2357.json, _data/chains/eip155-2358.json
A new Kroma Sepolia testnet is launched, so marked the existing one deprecated and added a new one.
This is our announcement link: https://medium.com/@kroma-network/kroma-second-testnet-is-live-e4b759ea65ca
=> mark to be deprecated the old testnet, and add a new Kroma Sepolia network

_data/chains/eip155-59140.json, _data/chains/eip155-59144.json
Hi! Following the PRs opened for Linea testnet a few weeks and months ago, we now would like to add support for **Linea mainnet**.
Please keep in mind that RPC endpoints, bridge and block explorer will be available in the upcoming weeks (hence the draft status).
Many thanks for support 🙂
=> Add linea mainnet

_data/chains/eip155-11155111.json
Adding `ethpandaops` and Infura RPCs (similar to Goerli) to Sepolia `rpc`s as `*.sepolia.org` RPCs have been down, as well as others in https://sepolia.dev/. 
It is difficult to find a working RPC as of writing and this can be discouraging to migrate to Sepolia for devs. Open to discuss what could be a better way.
=> Add rpc's to Sepolia

_data/chains/eip155-25.json
Cronos has exited the beta phase, and this request is to remove "Beta" from the Cronos Chain name.  
Official announcement: https://twitter.com/cronos_chain/status/1572932534257737728
=> Remove "Beta" from the Cronos Chain name

_data/chains/eip155-8453.json
Hello, this updates the Base mainnet RPC to be mainnet.base.org.
Related: #2318, #2320, #3165
=> Update Base mainnet RPC

_data/chains/eip155-10081.json
Hello,
Japan Open Chain Mainnet was merged 2 weeks ago. https://github.com/ethereum-lists/chains/pull/3222 
I propose to add Japan Open Chain Testnet in this PR.
Thank you for taking a look
=> Add Japan Open Chain Testnet

_data/chains/eip155-39.json
Update mainnet info for u2u chain
Network Name: U2U Solaris Mainnet
ChainID: 39
RPC: https://rpc-mainnet.uniultra.xyz/
Explorer: https://u2uscan.xyz/
=> Update mainnet info for u2u chain

_data/chains/eip155-91002.json
Changes the ``Nautilus Trition Testnet`` name from ``Nautilus Chain`` to ``Nautilus Trition Chain`` to avoid duplicate name
=> Fix Nautilus Triton testnet so it has a unique name

_data/chains/eip155-55004.json
This PR changes websocket endpoint for Titan's network, an optimistic rollup chain.
More information is available at [tokamak.network](https://tokamak.network/)
Thank you!
=> Change websocket endpoint for Titan chain mainnet

_data/chains/eip155-6.json, _data/chains/eip155-61.json, _data/chains/eip155-63.json
This PR:
* Deprecates Kotti ([core-geth](https://github.com/etclabscore/core-geth/pull/552) and [besu](https://github.com/hyperledger/besu/pull/5816) dropped support, its explorer was taken down and none validator stayed online)
* Removes faucets from ETC mainnet
* Adds faucets and aditional information for Mordor ETC testnet
=> Ethereum Classic networks clean up

_data/chains/eip155-444.json
Deprecates Frenchain Testnet, currently using Chain ID 444, in preparation of a new PR for an unrelated testnet to use chain ID 444. 
RPC is fully down. 
```
cast block latest --rpc-url https://rpc-01tn.frenchain.app
Error:
error sending request for url (https://rpc-01tn.frenchain.app/): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known
```
https://chainlist.org/chain/444
Explorer no longer exists (https://testnet.frenscan.io/), and redirects to https://app.tryethernal.com. 
Twitter account has been deleted: https://twitter.com/fren_chain, which is linked from the official site provided in the chain information: https://frenchain.app/
No tweets mention the Frenchain Testnet since November 2022.
=> Deprecate eip155-444.json

_data/chains/eip155-80001.json
https://matic-mumbai.chainstacklabs.com - Has been discontinued and no longer works
https://twitter.com/ChainstackHQ/status/1682027531917234179
---
https://matic-testnet-archive-rpc.bwarelabs.com - DNS entries no longer exist
ubuntu@ip-10-128-59-167:~/efs_gsn# ping matic-testnet-archive-rpc.bwarelabs.com
ping: matic-testnet-archive-rpc.bwarelabs.com: No address associated with hostname
=> Remove deprecated RPCs for Polygon Mumbai

_data/chains/eip155-30.json, _data/chains/eip155-31.json, _data/icons/rootstock.json
This pull request updates  [RSK](https://rootstock.io/) chain as its rebranded to [Rootstock](https://rootstock.io/). 
Reference: https://rootstock.io/
- Added blockscout url for Rootstock as it adheres to EIP3091
- Added rootstock ipfs icon and validated CIDs
- Specified icon size as per maintainer checklist
=> Update `Rootstock` Network

_data/chains/eip155-868.json
Our official info url: https://fantasiachain.com
=> Update Fantasia Chain infoURL

_data/chains/eip155-1.json
Description: Blocknative’s Transaction Boost protects users from frontrunning and sandwiching attacks without sacrificing visibility.
=> Adding Blocknative’s Transaction Boost RPC Endpoint

_data/chains/eip155-13337.json, _data/chains/eip155-4337.json
updated token info for networks `13337` and `4337` (Beam test- and mainnet), the gas token has been migrated. also added faucet and rpc links
=> chore: Beam network - gas token migration

_data/icons/fuse.json
Existing Fuse icon isn't displaying on ChainList:
https://chainlist.org/chain/122
ChainList is displaying an old Fuse icon. I update the IPFS URL which might solve this issue.
=> [Fuse] Update Fuse IPFS URL

_data/chains/eip155-1666600002.json, _data/chains/eip155-1666600003.json
Hello chains maintainers,
Harmony decided to shutdown shards 2 and 3, due to this I want to remove both of them.
Source: https://talk.harmony.one/t/hip30v2-update-announcement/23268
=> remove Harmony shards 2 and 3 due to HIP30, reason - https://talk.harmony.one/t/hip30v2-update-announcement/23268

_data/chains/eip155-46.json
This endpoint is no longer supported, so remove it from the RPC list.
=> Remove un-supported endpoint for the Darwinia Chain

_data/chains/eip155-570.json
As reported by the Syscoin Foundation https://github.com/DefiLlama/chainlist/commit/44bfcceedcbf288262139add171546038f57d7de, this RPC should be removed temporarily.
Note that ANKR provides both rpc.ankr.com/rollux and rollux.public-rpc.com
For reference: https://github.com/ethereum-lists/chains/pull/3787
=> Remove public ANKR RPC from Rollux mainnet.

_data/chains/eip155-295.json, _data/chains/eip155-296.json, _data/chains/eip155-297.json
Now HashScan redirects URLs as requested by [@ligi's comment](https://github.com/ethereum-lists/chains/pull/2279#discussion_r1108699662) in #2279.
This PR updates the explorer's URLs accordingly and flags them as EIP3091 compliant.
=> Updating HashScan's URLs

_data/chains/eip155-534351.json
After launch of Scoll mainnet, testnet URLs have changed.
=> Update Scroll Sepolia URLs

_data/chains/eip155-65010001.json, eip155-65010000.json
Adds 65010001 and deprecates 65010000
=> Update for new Autonity Bakerloo Testnet

_data/chains/eip155-20482050.json, _data/chains/eip155-8080808.json, _data/icons/hokum.json
**RPC:** https://mainnet.hokum.gg
**Chain ID:** 8080808
**Explorer:** https://explorer.hokum.gg
**RPC:** https://testnet.hokum.gg
**Chain ID:** 20482050
**Explorer:** https://testnet-explorer.hokum.gg
Hokum is rebranded from Modular Games
=> Add Hokum Mainnet and Testnet

_data/chains/eip155-148.json
I updated the ShimmerEVM name as it is called ShimmerEVM everywhere else which leads to problems like in the Metamask check for example
=> Update ShimmerEVM name

_data/chains/eip155-252.json, _data/chains/eip155-2522.json
We're renaming our chain to [Fraxtal](https://twitter.com/fraxfinance)
=> Rename fraxchain to fraxtal

_data/chains/eip155-199.json
https://rpc.bittorrentchain.io is not available, see: https://doc.bt.io/docs/networks/network.
=> Update rpc url in eip155-199.json

_data/chains/eip155-912559.json
Astria has cut a new devnet release, this updates the chain to point at the new release.
=> update astria dusknet to newest release

_data/chains/eip155-5678.json
We've changed the token symbol from `Unit` to `Tango` to avoid confusion and differentiate more clearly between token symbols on our testnet environments. Let me know if you have any questions. Thanks!
=> update Tanssi Testnet Token name

_data/chains/eip155-2410.json
Should be `Ether` and `ETH` since it's a eth L2
=> Changed native currency name and symbol to Ether and ETH from KRK

_data/chains/eip155-3068.json, _data/chains/eip155-49088.json
RPC, Bifrost Homepage, and Explorer URLs have been updated.
https://github.com/ethereum-lists/chains/pull/4258
In a previous PR, redirect from the old domain to a new domain is a good pattern, so I went ahead and did it.
However, for RPC, we will be migrating slowly as Hardhat, Metamask, Web3py, etc. do not detect redirects, so the existing domain (thebifrost.io) will be discontinued with further notice.
For now, the redirects from thebifrost.io to bifrostnetwork.com have mostly gone through except for rpc.
=> update domains for bifrost network

_data/chains/eip155-395.json
CamDL is blockchain network run by Ministry of Economy of Finance in Cambodia, with the initiative to provide the public a platform to experiment or develop any Web3 application to solve everyday problems or be part of the DeFi ecosystem.
=> Add CamDL Testnet

_data/chains/eip155-111188.json, _data/chains/eip155-18231.json, _data/chains/eip155-18233.json, _data/icons/real.json
Update data for Unreal testnet because
chainId changed. We had to move away from zkEVM Polygon CDK because it wasn't production ready, and we spinned up unreal with Arbitrum CDK.
=> Add support for re.al chain

_data/chains/eip155-397.json, _data/chains/eip155-398.json, _data/icons/near.json
Near is working on [a protocol change](https://github.com/near/NEPs/issues/518) to enable anyone with an Ethereum-compatible wallet to interact with Near-native dapps. To this end, Near requires its own chain ID separate from [Aurora](https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-1313161554.json).
=> Feat: Add Near chain

_data/chains/eip155-111188.json
Since the chain is now live, moving status to active.
=> Move re.al status to active

_data/chains/eip155-1995.json
Please review the request. We have updated RPC and explorer URL for edexa.network testnet.
=> updated edeXa testnet RPC URLs

_data/chains/eip155-17001.json, _data/chains/eip155-17069.json, _data/chains/eip155-690.json, _data/icons/garnet.json
Adds Redstone (ID 690) and the Garnet Holesky testnet (ID 17069). 
Also deprecates the old Redstone Holesky testnet and changes it's `shortname`.
=> Add Redstone and Garnet Holesky, deprecate Redstone Holesky testnet

_data/chains/eip155-13505.json
Related Gravity Alpha Mainnet PR is already merged - https://github.com/ethereum-lists/chains/pull/5118
This PR adds Gravity Alpha Testnet Sepolia
=> Add Gravity Alpha Testnet Sepolia

_data/chains/eip155-2043.json
OriginTrail Parachain is transformed into NeuroWeb after [a community Governance vote](https://neuroweb.subscan.io/referenda/5?tab=preimage) on OriginTrail Parachain in December 2023. Token name is changed from OTP to NEURO. Only names are changed, all technical details are same.
=> Update eip155-2043.json - Rename OriginTrail Parachain (OTP) to NeuroWeb (NEURO)

_data/chains/eip155-2777.json
Just reserve chain ID 2777 for GM Network Mainnet. 
We are still working on RPC and Explorer (Launching Mainnet).  and we will update its value ​​later next week.
=> Add chain ID 2777 for GM Network Mainnet

_data/chains/eip155-132902.json
This PR aims to add Form testnet to chainlist.
prettier ran successfully
gradlew run output:
=> Add Form testnet

_data/chains/eip155-1210.json, _data/icons/cuckoo-ai.json
This pull request adds the [Cuckoo Network](https://cuckoo.network)'s Testnet Sepolia to the chains registration. The explorer is available at [testnet-scan.cuckoo.network](https://testnet-scan.cuckoo.network/) and is EIP3091-compliant with blockscout.
Please review the changes and let me know if any adjustments are needed. Your feedback is highly appreciated.
Thank you for considering this pull request. I look forward to your positive response!
Best regards,
Lark
=> add cuckoo network / cuckoo ai testnet sepolia

_data/chains/eip155-44.json
The original explorer will be replaced with a new one, update the link here.
=> Update Crab network explorer link

_data/chains/eip155-1200.json
This pull request adds the [Cuckoo Network](https://cuckoo.network/)'s mainnet to the chains registration. The explorer is available at [mainnet-scan.cuckoo.network](https://mainnet-scan.cuckoo.network/) and is EIP3091-compliant with blockscout.
Please review the changes and let me know if any adjustments are needed. Your feedback is highly appreciated.
Thank you for considering this pull request. I look forward to your positive response!
Best regards,
Lark
=> add cuckoo chain mainnet

_data/chains/eip155-33102.json, _data/chains/eip155-33103.json
The PR adds a new Zilliqa 2 proto-testnet network to chainlist.
=> Add new zilliqa 2 proto-testnet network

_data/chains/eip155-12227331.json
Just deprecating a testnet.
I will create another PR to add a new chainId.
=> Deprecate Neo X testnet T3

_data/chains/eip155-12227332.json
We deprecated our previous testnet T3 here: #5485 
This PR adds a new chainId/networkId for testnet T4 (which should be the last testnet before mainnet).
=> Add NeoX Testnet T4

_data/eip155-388.json
This PR adds Cronos zkEVM mainnet (chain ID `388`) ahead of the mainnet deployment.
RPCs and explorers will be functional after the mainnet is live.
Details about Cronos zkEVM:
- [Documentation](https://docs-zkevm.cronos.org/)
- [GitHub Repo](https://github.com/cronos-labs/cronos-zkevm)
=> Adding Cronos zkEVM mainnet

_data/chains/eip155-41455.json, _data/icons/aleph-zero.json
This PR adds the Aleph Zero EVM Mainnet to the Chainlist.
- Name: Aleph Zero EVM
- RPC: https://rpc.alephzero.raas.gelato.cloud
- Chain ID: 41455
- Currency symbol: AZERO
- Explorer: https://evm-explorer.alephzero.org
Please let me know if any changes are needed. Thank you!
=> Add Aleph Zero EVM Mainnet

_data/chains/eip155-1001.json, _data/chains/eip155-8217.json
Updated Kaia symbol back to KLAY as the ticker is going to remain for a while until all exchanges updates.
Also updated the rpc endpoint according to https://docs.kaia.io/references/public-en/#public-json-rpc-endpoints-1
This is the previous PR https://github.com/ethereum-lists/chains/pull/5411 i created for updating the Ticker. But as per the discussion with the team, its decided to wait for a while for Ticker update.
Reference:
https://kaia.io
=> Updated KLAY Ticker

_data/chains/eip155-47763.json
Adding a second RPC endpoint to the `Neo X Mainnet` chain data that has initially been added in #5560.
=> Add RPC endpoint for Neo X Mainnet

_data/chains/eip155-254.json
changed native currency of swan chain from sETH to ETH to correctly reflect swan mainnet's native currency
=> changed native currency of swan chain

_data/chains/eip155-531050104.json
Hello!
We noticed a few adjustments were needed to the Sophon chain configuration, mainly to the native token (which is Sophon/SOPH, instead of ETH). Also added the missing websocket entrypoint.
=> chore: adjust Sophon chain configuration

_data/chains/eip155-42421.json
Asset Chain's network name isnt showing correctly in Trustwallet.
This change corrects that.
Thanks
=> Update Asset Chain testnet

_data/chains/eip155-13370.json
This PR adds support for the chain ID used by [Cannon](https://usecannon.com/), used by cannon CLI when hosting a local testnet. chain with its definitions and configurations.
=> add cannon chain

_data/icons/zenchain.json
Hi, we would like to update the icon in zenchain.json, associated with the `Zenchain Testnet` and `Zenchain` networks (chain id 8408 and 8108).
=> Update icon zenchain.json

_data/chains/eip155-570.json
Update includes the faucet link and explorer name.
=> Remove broken RPCs and update info - Rollux Mainnet

_data/chains/eip155-820.json, _data/icons/callistonetwork.json
-removed deprecated CE urls as they no longer support chain: https://github.com/CallistoEnterprise/PoWServers
-added Callisto DAO managed servers
-added icon
=> Callisto Network data update

_data/chains/eip155-1666600000.json
OnFinality has removed Harmony's RPC, so this endpoint is no longer valid:
`https://harmony.api.onfinality.io/public`
=> Remove Harmony Mainnet endpoint of Onfinality

_data/chains/eip155-210210.json, _data/icons/sorianTestnet.json
This pull request adds the Sorian Testnet chain to the Chainlist repository. The details of the chain are as follows:
Network Name: Sorian Testnet Network
Chain Name: Sorian Testnet Chain
Coin Name: Sorian Testnet
Symbol: tSOR
Decimals: 18
RPC URLs:
https://testnet-rpc.sorian.io/
https://testnet.rpc.sorian.io/
Chain ID: 210209
Explorer URL: https://testnet-scan.sorian.io
Info URL: https://mint.sorian.io/
Token Logo: ipfs://QmZmrcLYFtPZb36MZ1DyQpR7Lw8CWPP7x3Bx2anCjVWfMR
=> Add Sorian Testnet chain details

_data/chains/eip155-1001.json, _data/chains/eip155-8217.json
Updating the Ticker change from KLAY to KAIA. Please check the reference here https://www.binance.com/en/support/announcement/binance-will-support-the-kaia-klay-rebranding-to-kaia-kaia-f75f933759ee49d0af1dfbce7e32144c?hl=en .
Also updated the explorer urls for kaia network.
Thanks.
=> Update KAIA ticker and Explorer urls

_data/chains/eip155-48899.json
Updated Zircuit testnet RPC to use `https://`
=> Updated Zircuit testnet RPC

_data/chains/eip155-70701.json, _data/icons/pop-boss.json
This pull request includes the addition of a new chain configuration and its associated icon data. The most important changes include adding the configuration for the "Proof of Play - Boss" chain and adding its icon details.
Chain configuration:
* [`_data/chains/eip155-70701.json`](diffhunk://#diff-648add5b7fcd6e1db3cbfbc9b36d86a1582cc9a8aa1c73b08b055352823e17a9R1-R32): Added new chain configuration for "Proof of Play - Boss" with details such as `chainId`, `networkId`, `rpc`, `explorers`, and `parent` chain information.
Icon data:
* [`_data/icons/pop-boss.json`](diffhunk://#diff-4a2eba94f93589daedc0d8f3ac557f2b6e7fc11f5364b63acd6af79124ec094eR1-R8): Added icon details for the "Proof of Play - Boss" chain, including the URL, dimensions, and format of the icon.
=> Adds Proof of Play Boss Chain

_data/chains/eip155-282.json
@ligi, there's a new iteration of Cronos zkEVM testnet and the official chainId has changed from `282` to `240`. 
This PR is deprecating the older version of testnet. I will create another PR to add a new chainId.
=> Deprecate Old Version of Cronos zkEVM chain

_data/chains/eip155-24132016.json, _data/chains/eip155-241320161.json
Adds the XMTP mainnet and testnet chains
These chain IDs will be for the mainnet and testnet of the [XMTP](https://xmtp.org/) messaging AppChain
=> Add XMTP Chain

_data/chains/eip155-42261.json
To match official Oasis docs:
https://github.com/oasisprotocol/docs/blob/afc1f64/src/AddToMetaMask.tsx#L90-L94
This also matches how Oasis Sapphire symbol is named:
https://github.com/ethereum-lists/chains/blob/7cbf777d84336963b09c34175304bded9599dc21/_data/chains/eip155-23294.json#L8-L10
https://github.com/ethereum-lists/chains/blob/7cbf777d84336963b09c34175304bded9599dc21/_data/chains/eip155-23295.json#L11-L13
cc @matevz
=> Update Oasis Emerald Testnet symbol

_data/chains/eip155-7744.json, _data/icons/phron.json
This pull request adds the  Phron Testnet to the Chainlist.
Chain Details:
Chain Name: Phron Testnet
Chain ID: 7744
RPC URL: https://testnet.phron.ai
Symbol: TPHR
Currency Symbol: PHR
We welcome any feedback or suggestions to improve the integration. Thank you for considering our addition to Chainlist!
=> Add Phron Testnet to Chainlist

_data/chains/eip155-63000.json
- eCredits was rebranded to eSync Network. Previously it was only done for testnet, now also mainnet.
- added additional RPC endpoint with new esync.network domain
=> Rebranding: eCredits to eSync Network

_data/chains/eip155-11822.json
fix: add OKX Explorer to Artela TestNet.
Artela Website: https://artela.network/
Artela Twitter: https://twitter.com/Artela_Network
thanks🙏
=> Add OKX Explorer to Artela TestNet

_data/chains/eip155-9091.json, _data/icons/koppa.json
This pull request adds the KPA Smart Chain Testnet to the Ethereum Chains repository.
Details of the addition:
Chain Name: KPA Smart Chain Testnet
Symbol: tKPA
Chain ID: 9091
RPC URLs:
https://testnet-rpc1.koppachain.com/
https://testnet-rpc2.koppachain.com/
https://testnet-rpc3.koppachain.com/
https://testnet-rpc4.koppachain.com/
Native Currency: KPA Smart Chain Testnet (tKPA)
Faucet URL: [Mint KPA](https://mint.koppachain.com/)
Info URL: [KoppaChain](https://koppachain.com/)
Explorer URL: [KPA Scan](https://testnet.kpascan.com/)
Icon: The icon for the KPA Smart Chain Testnet has been added.
This addition aims to enhance the ecosystem of supported chains and provide developers with access to the KPA Smart Chain Testnet for testing and development.
=> Add KPA Smart Chain Testnet

_data/chains/eip155-56288.json
Boba BNB settles to BNB chain, not Goerli
=> Fix Boba BNB L2 parent

_data/chains/eip155-300.json
kzSync Sepolia settles to Sepolia, not Mainnet
=> fix kzSync sepolia l2 parent

_data/chains/eip155-15557.json, _data/chains/eip155-17777.json
And neither is testnet.
It's connected to EOS Native chain, which is not EVM chain.
=> EOS EVM is not Mainnet L2 rollup

_data/chains/eip155-98864.json, _data/icons/plume.json
Adds the latest version of Plume devnet, which supersedes the deprecated Plume testnet removed in #6250: https://x.com/plumenetwork/status/1834623547496714340
=> add Plume devnet

_data/chains/eip155-1001.json
Updated Testnet RPC url as per below Kaia docs
https://docs.kaia.io/references/public-en/#testnet-kairos-public-json-rpc-endpoints
=> Updated Kaia Testnet rpc endpoint

_data/chains/eip155-1923.json, _data/chains/eip155-1924.json
old: Swell Network
new: Swellchain
I've run the prettier and the RPC format is different for the mainnet and testnet (single line vs multiline)
just lmk if you want to have it changed-  idc tbh @ligi 
(der commit typo bleibt jetzt bitte für ewig, hehe)
=> update: Swellchain definitions

_data/chains/eip155-11155111.json
This pull request adds a new RPC endpoint for the Sepolia Testnet to support testing and development activities. The RPC is provided by Alchemy and offers reliable access to the Sepolia Ethereum Testnet.
Changes
Updated file: _data/chains/eip155-11155111.json
Added the following RPC URL:
https://eth-sepolia.g.alchemy.com/v2/WddzdzI2o9S3COdT73d5w6AIogbKq4X-
Purpose
This RPC addition aims to enhance accessibility and improve developer experience when interacting with the Sepolia Testnet. The Alchemy RPC ensures stability and performance during testing.
Reference
RPC Provider Website: [Alchemy](https://www.alchemy.com/)
Network Name: Sepolia Testnet
Chain ID: 11155111
=> add GRAPHIX RPC for sepolia testnet

_data/chains/eip155-2035.json
Phala is going to be a L2 with Ether as the gas fee token. Update the config to reflect it.
=> Update Phala Network

_data/chains/eip155-65100004.json
Fix slight typo in autonity-apis urls, correcting `picadilly` to `piccadilly`
=> Autonity Update for autonity-apis

_data/chains/eip155-945.json, _data/chains/eip155-964.json
This PR changes some info for testnet added in #5798 and adds the mainnet chainID as well.
=> Add Bittensor (TAO) EVM-enabled mainnet

_data/chains/eip155-490000.json, _data/icons/autonomys.json
This PR is related to the update of a network that was deployed using a Chain ID that already exists and is registered in ChainList. The issue is that this network is now deprecated, and the same team, Autonomys, has reused this Chain ID for the deployment of the Autonomys Taurus Testnet.
=> Add Autonomys Taurus

package.json
This PR adds a very basic `package.json` file at the root so this repo can be installed in JS projects using the repo URL:
```bash
npm install https://github.com/ethereum-lists/chains.git
```
After running the command above, data in the repo will be accessible as such:
```typescript
// Accessing data in `_data/chains/`
import mainnet from "@ethereum-lists/chains/eip155-1.json" with { type: "json" };
console.log(mainnet); // { name: "Ethereum Mainnet", ... }
// Accessing data in `_data/icons/`
import mainnetIcons from "@ethereum-lists/chains/icons/ethereum.json" with { type: "json" };
console.log(mainnetIcons); // [{ url: "ipfs://...", ... }, ...]
// Accessing data in `_data/iconsDownload/`
import fs from "fs";
const icon = fs.readFileSync(new …
```
=> Add `package.json`

_data/chains/eip155-8844.json
The PR includes an update of the Testnet faucet and rpc URLs that has to be made because of DNS problems
=> Update Hydra Testnet faucet and RPC URLs because of DNS issues

_data/chains/eip155-80094.json
this is a placeholder in order for the chain to launch
=> update(chains): add berachain chainId

_data/chains/eip155-302.json
Updating the name of the ZKcandy Sepolia Testnet from "zkCandy" to "ZKcandy" to match documentation and keep branding consistent.
Source: https://litepaper.zkcandy.io
=> Update title case for ZKcandy

_data/chains/eip155-420420421.json
Update url to https://westend-asset-hub-eth-explorer.parity.io
This redirects to subscan and extract the proper explorer url from the provided transaction hash
=> Update Block Explorer URL for eip155-420420421.json

_data/chains/eip155-1523903251.json, _data/chains/eip155-490092.json
I have added Haust Network Testnet Chain. Please find the Icon for the network in the _data/icons/haust.json directory of the upstream repository.
=> Added Haust Network Testnet chain

_data/chains/eip155-167000.json, _data/chains/eip155-167009.json
@ligi we have recently changed the name of our existing Taiko Mainnet to Taiko Alethia, You can find it here: https://docs.taiko.xyz/core-concepts/what-is-taiko-alethia/
Also changed the name of Taiko Hekla L2 to "Taiko Hekla" for uniformity.
=> feat(docs): change name of taiko mainnet and testnet

.github/workflows/prettier_check.yml, .github/workflows/validate_json.yml
Github is currently doing a brownout period for cache V2 which is causing PR checks to fail.
https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down
=> Update to GH Actions V4

_data/chains/eip155-61022448.json
This PR adds a new chain entry to the ethereum-lists/chains repository, based on the CAIP‑2 standard.
Chain Information
Chain Name: dKargo Warehouse Testnet
Chain ID: eip155:61022448
Network Characteristics: An L3 Rollup chain built on Arbitrum Sepolia
This chain entry follows the CAIP‑2 specification for defining a unique chain identifier in the format <namespace>:<reference>. The new chain is intended to support testing and scalability within the dKargo ecosystem. For further details, please refer to the [CAIP‑2 specification](https://github.com/ChainAgnostic/CAIPs/blob/main/CAIPs/caip-2.md?plain=1).
=> Add new chain: eip155:61022448 (Dkargo testnet: warehouse)

_data/chains/eip155-9369.json
I have updated the custom domain names for RPC, Blockscout, and bridge.
=> updated domain name for z-chain

_data/chains/eip155-80084.json
Berachain has deprecated Bartio recently, updated data to reflect this.
=> chore: deprecate bartio

_data/chains/eip155-863.json
- Chain Name: Radius Testnet
- Chain ID: 863
- RPC URL: https://dev-secure.rpc.theradius.xyz
- Block Explorer: (None for now)
- Native Currency: Useless (USLS)
=> Add chain ID 863 - Radius Testnet

_data/chains/eip155-5424.json
The old RPCs remain accessible for now, but these are the new preferred ones.
=> Updated edexa mainnet rpcs

_data/chains/eip155-98865.json
Superseded by the new deployment in #6967.
=> mark chain ID 98865 as legacy

_data/chains/eip155-1995.json
The old RPCs remain accessible for now, but these are the new preferred ones.
=> Updated edeXa testnet rpcs

_data/chains/eip155-54176.json
`rpc2.overprotocol.com` is deprecated.
=> Remove deprecated rpc of overprotocol mainnet

_data/chains/eip155-7869.json
Context: https://x.com/Powerloom/status/1897669070688022845
`TL;DR: OP Stack has discontinued support for custom gas tokens. Powerloom has a new Arbitrum Orbit based chain with a new chainid but same icon. The older chain will continue to run until migration is complete`
=> Add Powerloom Mainnet V2

_data/chains/eip155-2340.json
Added Fastnode’s public endpoint for Atleta Testnet. No breaking changes or modifications to existing functionality.
=> Added Fastnode's public endpoint for Atleta Testnet

_data/chains/eip155-8108.json, _data/chains/eip155-8408.json
Hi,
The ZenChain network is updating its native currency symbol from ZCX to ZTC.
Thank you,
Kris Bitney
=> Update ZCX to ZTC for ZenChain

_data/chains/eip155-7210.json, _data/chains/eip155-7222.json
Deprecates testnet-1 and devnet-3
=> chore: deprecate testnet-1 and devnet 3 Nibiru chains

_data/chains/eip155-6934.json, _data/icons/xyl-test.json, _data/icons/xylume-testnet.json
XYL TestNet just got a v3, and is now renamed to Xylume TestNet. New Icon and information has been updated.
=> Rename XYL TestNet to Xylume TestNet, and update icon and info.

_data/chains/eip155-161221135.json, _data/chains/eip155-98864.json, _data/chains/eip155-98865.json, _data/chains/eip155-98866.json, _data/chains/eip155-98867.json
Adds the newest version of Plume testnet, which supersedes and deprecates the previous versions of Plume testnet and Plume devnet.
=> add new Plume testnet

_data/chains/eip155-1440002.json, _data/chains/eip155-1449000.json, _data/icons/xrplevm.json
**Title:** Add XRPLEVM Testnet and update Devnet, Icon, and Faucet (#7053)
**Summary of Changes:**
- **Add XRPL EVM Sidechain Testnet**: Introduces a new chain file `eip155-1449000.json` for the XRPLEVM Testnet, including RPC endpoints, faucets, and an explorer.
- **Update XRPLEVM Devnet**: Changes the faucet URL from `https://chains.tools/faucet/xrplevm` to `https://faucet.xrplevm.org` in `eip155-1440002.json`.
- **Revise Icon Metadata**: Updates the icon file `xrplevm.json` with a new IPFS URL and adjusts dimensions for consistency.
**Details:**
- **Testnet Chain File (`eip155-1449000.json`)**:
- **Name**: `XRPL EVM Sidechain Testnet`
- **Chain ID / Network ID**: `1449000`
- **Native Currency**: `XRP`
- **RPC URLs**: `https://rpc.testnet.xrplevm.org` and `https://ws.testnet.xrplevm.org` …
=> Add XRPLEVM Testnet and update: Devnet, Icon and faucet.

_data/chains/eip155-9496.json, _data/icons/loadnetwork.json, _data/icons/weavevm.json
WeaveVM rebranded to Load Network (https://blog.load.network/weavevm-is-now-load-network/). 
This PR updates the 9496 metadata and adds a new loadnetwork icon.
=> add Load Network chain and icon

_data/chains/eip155-11155111.json
Remove the wrong RPC URL in sepolia RPC urls list (eip155-11155111.json)
closes #7194
=> remove wrong RPC endpoint for Sepolia

_data/chains/eip155-2522.json
Following our [North Star proposal](https://gov.frax.finance/t/fip-428-frax-north-star-proposal-v2/3652) the native currency  of the testnet changed to Frax (FRAX). Mainnet will soon follow on the 29th.
=> Update fraxtal testnet native currency

_data/chains/eip155-369.json
The updated URL is EIP3091 compliant. Previous URL pointed to a link page.
=> Update PulseChain explorer and icon

_data/chains/eip155-128123.json
New link: https://testnet.explorer.etherlink.com/
Source: https://docs.etherlink.com/get-started/network-information
=> Update block explorer for chainId 128123

_data/chains/eip155-1660990954.json
Hello team!
Doing this PR to remove a legacy endpoint of Status Network Sepolia Testnet.
We followed the guide and the maintainer checklist so hopefully all is good!
Many thanks,
the Status Network team
=> Remove RPC link from Status Network Sepolia - chainId: 1660990954

_data/chains/eip155-3338.json
Description:
•	Updated peaq chain RPC endpoints by removing deprecated and non-functional URLs.
•	Added/kept only reliable and active RPC endpoints for improved stability and performance.
•	Updated infoURL from https://www.peaq.network to the new domain https://www.peaq.xyz to reflect the latest official project site.
Summary of changes:
•	Removed: https://peaq.api.onfinality.io/public, https://evm.peaq.network
•	Updated: infoURL to new domain
This update ensures up-to-date endpoints and official info link for users and integrators.
=> Update RPC endpoints and infoURL for peaq

_data/chains/eip155-3338.json
Update peaq RPC Endpoints
Summary:
Removes the deprecated https://peaq-rpc.publicnode.com endpoint
from the Peaq mainnet (chainId 3338) RPC list. No other changes.
Details:
• Removed deprecated RPC URL https://peaq-rpc.publicnode.com
=> peaq: remove deprecated PublicNode RPC endpoint

_data/chains/eip155-6934.json
Updated the Xylume TestNet RPC URL.
Old: https://xyl-testnet.glitch.me/rpc/
New: https://xylume-testnet.sparked.network/rpc/
=> Update Xylume TestNet RPC

_data/chains/eip155-9745.json, _data/icons/plasma.json
- Added Plasma Mainnet configuration with chain ID 9745
- Updated Plasma Testnet (9746) with correct explorer URL and shortName
- Added Plasma icon (SVG) for both networks
- Mainnet RPC and explorer URLs are temporarily empty pending live deployment
- Both chains use Routescan as the explorer provider
- Icon uploaded to IPFS: bafkreicgr636cvsomnqj3ikgdpixfv7eh2nr2u3k7v423raav2lrpsvfwy
=> Add Plasma Mainnet (9745) and update Testnet configuration

_data/chains/eip155-869.json, _data/icons/worldmobilechain.json
This PR updates the metadata for the World Mobile Chain Mainnet (chainId: 869) with the following changes:
Chain Status: 
* Changed chain status from incubating to active 
Explorer: 
* Added Explorer for World Mobile Chain Mainnet. 
RPC Updates:
* Add Public RPC for the Chain
Icon: 
* Add Icon for World Mobile Chain 
Thank you for your time and assistance :)
=> Update World Mobile Chain - Info, RPC, Explorer and Icon

_data/chains/eip155-100021.json
Add Sova Mainnet (chainId: 100021)
Parent chain: ETH Mainnet (1)
Native currency: ETH (18 decimals)
=> Add: Sova Mainnet config (chainId: 100021)

_data/chains/eip155-5734951.json
Update Jovay network default public rpc endpoint
Hello Team!
I've updated the data for Jovay Mainnet.
Changes:
Updated the default rpc endpoint for the Jovay Mainnet network.
=> Update Jovay mainnet network config
